;
; File generated by cc65 v 2.17 - Git 582aa41
;
	.fopt		compiler,"cc65 v 2.17 - Git 582aa41"
	.setcpu		"65SC02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_clearerr
	.import		_fseek
	.export		_rewind

; ---------------------------------------------------------------
; void __near__ __fastcall__ rewind (__near__ struct _FILE *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rewind: near

.segment	"CODE"

	jsr     pushax
	jsr     pushw0sp
	jsr     pushl0
	lda     #$02
	jsr     _fseek
	jsr     ldax0sp
	jsr     _clearerr
	jmp     incsp2

.endproc

