# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/University/EISD/06_sources/2_hls_and_SoC/overlays/design_adder/design_adder.srcs/sources_1/bd/design_adder/ip/design_adder_rst_processing_system7_0_100M_0/design_adder_rst_processing_system7_0_100M_0.xci
# IP: The module: 'design_adder_rst_processing_system7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/University/EISD/06_sources/2_hls_and_SoC/overlays/design_adder/design_adder.srcs/sources_1/bd/design_adder/ip/design_adder_rst_processing_system7_0_100M_0/design_adder_rst_processing_system7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_adder_rst_processing_system7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/University/EISD/06_sources/2_hls_and_SoC/overlays/design_adder/design_adder.srcs/sources_1/bd/design_adder/ip/design_adder_rst_processing_system7_0_100M_0/design_adder_rst_processing_system7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_adder_rst_processing_system7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/University/EISD/06_sources/2_hls_and_SoC/overlays/design_adder/design_adder.srcs/sources_1/bd/design_adder/ip/design_adder_rst_processing_system7_0_100M_0/design_adder_rst_processing_system7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_adder_rst_processing_system7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/University/EISD/06_sources/2_hls_and_SoC/overlays/design_adder/design_adder.srcs/sources_1/bd/design_adder/ip/design_adder_rst_processing_system7_0_100M_0/design_adder_rst_processing_system7_0_100M_0.xci
# IP: The module: 'design_adder_rst_processing_system7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/University/EISD/06_sources/2_hls_and_SoC/overlays/design_adder/design_adder.srcs/sources_1/bd/design_adder/ip/design_adder_rst_processing_system7_0_100M_0/design_adder_rst_processing_system7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_adder_rst_processing_system7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/University/EISD/06_sources/2_hls_and_SoC/overlays/design_adder/design_adder.srcs/sources_1/bd/design_adder/ip/design_adder_rst_processing_system7_0_100M_0/design_adder_rst_processing_system7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_adder_rst_processing_system7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/University/EISD/06_sources/2_hls_and_SoC/overlays/design_adder/design_adder.srcs/sources_1/bd/design_adder/ip/design_adder_rst_processing_system7_0_100M_0/design_adder_rst_processing_system7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_adder_rst_processing_system7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
