;
; File generated by cc65 v 2.17 - Git 582aa41
;
	.fopt		compiler,"cc65 v 2.17 - Git 582aa41"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_exit
	.import		_strlen
	.import		_clrscr
	.import		_kbhit
	.import		_gotoxy
	.import		_wherex
	.import		_cputc
	.import		_cputcxy
	.import		_cputsxy
	.import		_cgetc
	.import		_cursor
	.import		_revers
	.import		_textcolor
	.import		_bgcolor
	.import		_bordercolor
	.import		_chline
	.import		_chlinexy
	.import		_cvlinexy
	.import		_cclearxy
	.import		_cputhex8
	.import		_cputhex16
	.import		_isalnum
	.import		_isdigit
	.import		_isxdigit
	.import		_toupper
	.import		_brk_a
	.import		_brk_x
	.import		_brk_y
	.import		_brk_sr
	.import		_brk_pc
	.import		_DbgDisAsm
	.import		_DbgDisAsmLen
	.import		_DbgIsRAM
	.import		_DbgMemDump
	.import		_DbgSP
	.import		_DbgCS
	.import		_DbgHI
	.export		_DbgBreakCount
	.export		_DbgBreaks
	.import		_DbgGetBreakSlot
	.import		_DbgIsBreak
	.export		_DbgEntry

.segment	"DATA"

_ActiveFrame:
	.word	$FFFF
_ActivePrompt:
	.word	$0000
_DbgBreakCount:
	.byte	$00

.segment	"RODATA"

_RegText:
	.byte	$01
	.byte	$00
	.addr	L0009
	.byte	$01
	.byte	$01
	.addr	L000D
	.byte	$01
	.byte	$02
	.addr	L0011
	.byte	$01
	.byte	$03
	.addr	L0015
	.byte	$01
	.byte	$04
	.addr	L0019
	.byte	$01
	.byte	$05
	.addr	L001D
	.byte	$01
	.byte	$06
	.addr	L0021
	.byte	$01
	.byte	$07
	.addr	L0025
_HelpText:
	.byte	$01
	.byte	$00
	.addr	L0029
	.byte	$01
	.byte	$01
	.addr	L002D
	.byte	$01
	.byte	$02
	.addr	L0031
	.byte	$01
	.byte	$03
	.addr	L0035
	.byte	$01
	.byte	$04
	.addr	L0039
	.byte	$01
	.byte	$05
	.addr	L003D
	.byte	$01
	.byte	$06
	.addr	L0041
	.byte	$01
	.byte	$07
	.addr	L0045
	.byte	$01
	.byte	$08
	.addr	L0049
	.byte	$01
	.byte	$09
	.addr	L004D
	.byte	$01
	.byte	$0A
	.addr	L0051
	.byte	$01
	.byte	$0B
	.addr	L0055
	.byte	$01
	.byte	$0C
	.addr	L0059
	.byte	$01
	.byte	$0D
	.addr	L005D
	.byte	$01
	.byte	$0E
	.addr	L0061
	.byte	$01
	.byte	$0F
	.addr	L0065
	.byte	$01
	.byte	$10
	.addr	L0069
	.byte	$01
	.byte	$11
	.addr	L006D
_AsmFrame:
	.byte	$B0
	.byte	$B2
	.byte	$AB
	.byte	$DB
	.byte	$00
	.byte	$00
	.byte	$1E
	.byte	$0F
	.byte	$1D
	.byte	$0E
	.byte	$01
	.addr	_AsmHandler
	.byte	$00
	.word	$0000
_RegFrame:
	.byte	$B2
	.byte	$AE
	.byte	$AB
	.byte	$B3
	.byte	$1E
	.byte	$00
	.byte	$27
	.byte	$09
	.byte	$08
	.byte	$08
	.byte	$01
	.addr	_RegHandler
	.byte	$08
	.addr	_RegText
_StackFrame:
	.byte	$AB
	.byte	$B3
	.byte	$DB
	.byte	$B3
	.byte	$1E
	.byte	$09
	.byte	$27
	.byte	$0F
	.byte	$08
	.byte	$05
	.byte	$01
	.addr	_StackHandler
	.byte	$00
	.word	$0000
_CStackFrame:
	.byte	$DB
	.byte	$B3
	.byte	$B1
	.byte	$BD
	.byte	$1E
	.byte	$0F
	.byte	$27
	.byte	$18
	.byte	$08
	.byte	$08
	.byte	$01
	.addr	_CStackHandler
	.byte	$00
	.word	$0000
_DumpFrame:
	.byte	$AB
	.byte	$DB
	.byte	$AD
	.byte	$B1
	.byte	$00
	.byte	$0F
	.byte	$1E
	.byte	$18
	.byte	$1D
	.byte	$08
	.byte	$01
	.addr	_DumpHandler
	.byte	$00
	.word	$0000
_HelpFrame:
	.byte	$B0
	.byte	$AE
	.byte	$AD
	.byte	$BD
	.byte	$00
	.byte	$00
	.byte	$27
	.byte	$18
	.byte	$26
	.byte	$17
	.byte	$00
	.addr	_HelpHandler
	.byte	$12
	.addr	_HelpText
_Frames:
	.addr	_AsmFrame
	.addr	_RegFrame
	.addr	_StackFrame
	.addr	_CStackFrame
	.addr	_DumpFrame
	.addr	_HelpFrame
L0031:
	.byte	$C6,$33,$2C,$20,$55,$20,$20,$20,$20,$20,$D2,$55,$4E,$20,$55,$4E
	.byte	$54,$49,$4C,$20,$53,$55,$42,$52,$4F,$55,$54,$49,$4E,$45,$20,$52
	.byte	$45,$54,$55,$52,$4E,$53,$00
L0212:
	.byte	$C3,$41,$4E,$4E,$4F,$54,$20,$53,$45,$54,$20,$42,$52,$45,$41,$4B
	.byte	$50,$4F,$49,$4E,$54,$20,$2D,$20,$50,$52,$45,$53,$53,$20,$41,$20
	.byte	$4B,$45,$59,$00
L0226:
	.byte	$D4,$4F,$4F,$20,$4D,$41,$4E,$59,$20,$42,$52,$45,$41,$4B,$50,$4F
	.byte	$49,$4E,$54,$53,$20,$2D,$20,$50,$52,$45,$53,$53,$20,$41,$20,$4B
	.byte	$45,$59,$00
L006D:
	.byte	$53,$20,$20,$20,$20,$20,$20,$20,$20,$20,$D3,$4B,$49,$50,$20,$4E
	.byte	$45,$58,$54,$20,$49,$4E,$53,$54,$52,$55,$43,$54,$49,$4F,$4E,$00
L0041:
	.byte	$31,$2D,$35,$20,$20,$20,$20,$20,$20,$20,$D3,$45,$4C,$45,$43,$54
	.byte	$20,$41,$43,$54,$49,$56,$45,$20,$57,$49,$4E,$44,$4F,$57,$00
L0061:
	.byte	$50,$20,$20,$20,$20,$20,$20,$20,$20,$20,$D5,$53,$45,$20,$41,$53
	.byte	$20,$4E,$45,$57,$20,$D0,$C3,$20,$56,$41,$4C,$55,$45,$00
L0059:
	.byte	$46,$20,$20,$20,$20,$20,$20,$20,$20,$20,$C6,$4F,$4C,$4C,$4F,$57
	.byte	$20,$49,$4E,$53,$54,$52,$55,$43,$54,$49,$4F,$4E,$00
L002D:
	.byte	$C6,$32,$2C,$20,$54,$20,$20,$20,$20,$20,$D4,$4F,$47,$47,$4C,$45
	.byte	$20,$42,$52,$45,$41,$4B,$50,$4F,$49,$4E,$54,$00
L020D:
	.byte	$C9,$4E,$56,$41,$4C,$49,$44,$20,$49,$4E,$50,$55,$54,$20,$2D,$20
	.byte	$50,$52,$45,$53,$53,$20,$41,$20,$4B,$45,$59,$00
L0174:
	.byte	$D0,$52,$45,$53,$53,$20,$41,$4E,$59,$20,$4B,$45,$59,$20,$54,$4F
	.byte	$20,$43,$4F,$4E,$54,$49,$4E,$55,$45,$00
L0035:
	.byte	$C6,$34,$2C,$20,$48,$20,$20,$20,$20,$20,$D2,$55,$4E,$20,$54,$4F
	.byte	$20,$43,$55,$52,$53,$4F,$52,$00
L0069:
	.byte	$52,$20,$20,$20,$20,$20,$20,$20,$20,$20,$D2,$45,$44,$52,$41,$57
	.byte	$20,$53,$43,$52,$45,$45,$4E,$00
L0051:
	.byte	$41,$2F,$5A,$20,$20,$20,$20,$20,$20,$20,$CD,$4F,$56,$45,$20,$55
	.byte	$50,$2F,$44,$4F,$57,$4E,$00
L004D:
	.byte	$C3,$55,$52,$53,$4F,$52,$20,$20,$20,$20,$CD,$4F,$56,$45,$20,$55
	.byte	$50,$2F,$44,$4F,$57,$4E,$00
L005D:
	.byte	$4F,$20,$20,$20,$20,$20,$20,$20,$20,$20,$C7,$4F,$54,$4F,$20,$4F
	.byte	$52,$49,$47,$49,$4E,$00
L0039:
	.byte	$C6,$37,$2C,$20,$53,$50,$41,$43,$45,$20,$D3,$54,$45,$50,$20,$49
	.byte	$4E,$54,$4F,$00
L003D:
	.byte	$C6,$38,$2C,$20,$45,$4E,$54,$45,$52,$20,$D3,$54,$45,$50,$20,$4F
	.byte	$56,$45,$52,$00
L0045:
	.byte	$2B,$20,$20,$20,$20,$20,$20,$20,$20,$20,$D0,$41,$47,$45,$20,$44
	.byte	$4F,$57,$4E,$00
L0055:
	.byte	$43,$20,$20,$20,$20,$20,$20,$20,$20,$20,$C3,$4F,$4E,$54,$49,$4E
	.byte	$55,$45,$00
L0049:
	.byte	$2D,$20,$20,$20,$20,$20,$20,$20,$20,$20,$D0,$41,$47,$45,$20,$55
	.byte	$50,$00
L0170:
	.byte	$D0,$52,$45,$53,$53,$20,$C6,$31,$20,$46,$4F,$52,$20,$48,$45,$4C
	.byte	$50,$00
L0065:
	.byte	$51,$20,$20,$20,$20,$20,$20,$20,$20,$20,$D1,$55,$49,$54,$00
L0029:
	.byte	$C6,$31,$2C,$20,$3F,$20,$20,$20,$20,$20,$C8,$45,$4C,$50,$00
L0207:
	.byte	$C7,$4F,$54,$4F,$3A,$20,$00
L000D:
	.byte	$D3,$D2,$00
L0021:
	.byte	$C3,$D3,$00
L0025:
	.byte	$C8,$C9,$00
L001D:
	.byte	$D3,$D0,$00
L03A8:
	.byte	$2D,$3E,$00
L0009:
	.byte	$D0,$C3,$00
L0015:
	.byte	$D8,$00
L0011:
	.byte	$C1,$00
L0019:
	.byte	$D9,$00

.segment	"BSS"

_AsmAddr:
	.res	2,$00
_DumpAddr:
	.res	2,$00
_CStackAddr:
	.res	2,$00
_StackAddr:
	.res	1,$00
_PromptColor:
	.res	1,$00
_PromptLength:
	.res	1,$00
_DbgBreaks:
	.res	48,$00

; ---------------------------------------------------------------
; unsigned char __near__ AsmHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmHandler: near

.segment	"CODE"

	jsr     decsp3
L02E8:	jsr     _UpdateAsm
	jsr     stax0sp
	jsr     _GetKeyUpdate
	ldy     #$02
	sta     (sp),y
	cmp     #$11
	jeq     L0319
	cmp     #$2B
	beq     L02F3
	cmp     #$2D
	beq     L02F7
	cmp     #$41
	beq     L0311
	cmp     #$46
	beq     L0303
	cmp     #$47
	beq     L0306
	cmp     #$4F
	beq     L030A
	cmp     #$50
	beq     L030D
	cmp     #$54
	beq     L02FD
	cmp     #$5A
	beq     L0319
	cmp     #$91
	beq     L0311
	cmp     #$E1
	beq     L02FD
	jmp     L0501
L02F3:	jsr     ldax0sp
	sta     _AsmAddr
	stx     _AsmAddr+1
	jmp     L02E8
L02F7:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     pushax
	lda     _AsmFrame+9
	jsr     _AsmBack
	sta     _AsmAddr
	stx     _AsmAddr+1
	jmp     L02E8
L02FD:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     _DbgToggleUserBreak
	jmp     L02E8
L0303:	jsr     _AsmFollow
	jmp     L02E8
L0306:	lda     #<(_AsmAddr)
	ldx     #>(_AsmAddr)
	jsr     _InputGoto
	jmp     L02E8
L030A:	jsr     _AsmHome
	jmp     L02E8
L030D:	lda     _AsmAddr+1
	sta     _brk_pc+1
	lda     _AsmAddr
	sta     _brk_pc
	jmp     L02E8
L0311:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     pushax
	lda     #$01
	jsr     _AsmBack
	sta     _AsmAddr
	stx     _AsmAddr+1
	jmp     L02E8
L0319:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     _DbgDisAsmLen
	clc
	adc     _AsmAddr
	sta     _AsmAddr
	txa
	adc     _AsmAddr+1
	sta     _AsmAddr+1
	jmp     L02E8
L0501:	ldx     #$00
	lda     (sp),y
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ RegHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_RegHandler: near

.segment	"CODE"

	jmp     _GetKeyUpdate

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ StackHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_StackHandler: near

.segment	"CODE"

	jsr     decsp1
	lda     _StackFrame+9
	jsr     pusha
L0373:	jsr     _GetKeyUpdate
	ldy     #$01
	sta     (sp),y
	cmp     #$11
	beq     L038C
	cmp     #$2B
	beq     L037C
	cmp     #$2D
	beq     L0380
	cmp     #$41
	beq     L0387
	cmp     #$4F
	beq     L0384
	cmp     #$5A
	beq     L038C
	cmp     #$91
	beq     L0387
	jmp     L0502
L037C:	dey
	lda     (sp),y
	clc
	adc     _StackAddr
	sta     _StackAddr
	jmp     L037A
L0380:	dey
	lda     (sp),y
	eor     #$FF
	sec
	adc     _StackAddr
	sta     _StackAddr
	jmp     L037A
L0384:	jsr     _StackHome
	jmp     L037A
L0387:	dec     _StackAddr
	jmp     L037A
L038C:	inc     _StackAddr
	jmp     L037A
L0502:	ldx     #$00
	lda     (sp),y
	jmp     incsp2
L037A:	jsr     _UpdateStack
	jmp     L0373

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ CStackHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_CStackHandler: near

.segment	"CODE"

	jsr     decsp1
	lda     _CStackFrame+9
	asl     a
	jsr     pusha
L03B3:	jsr     _GetKeyUpdate
	ldy     #$01
	sta     (sp),y
	cmp     #$11
	beq     L03CE
	cmp     #$2B
	beq     L03BC
	cmp     #$2D
	beq     L03C0
	cmp     #$41
	beq     L03C7
	cmp     #$4F
	beq     L03C4
	cmp     #$5A
	beq     L03CE
	cmp     #$91
	beq     L03C7
	jmp     L0503
L03BC:	dey
	lda     (sp),y
	clc
	adc     _CStackAddr
	sta     _CStackAddr
	tya
	adc     _CStackAddr+1
	sta     _CStackAddr+1
	jmp     L03BA
L03C0:	dey
	lda     (sp),y
	eor     #$FF
	sec
	adc     _CStackAddr
	sta     _CStackAddr
	lda     #$FF
	adc     _CStackAddr+1
	sta     _CStackAddr+1
	jmp     L03BA
L03C4:	jsr     _CStackHome
	jmp     L03BA
L03C7:	lda     _CStackAddr
	sec
	sbc     #$02
	sta     _CStackAddr
	bcs     L03BA
	dec     _CStackAddr+1
	jmp     L03BA
L03CE:	lda     #$02
	clc
	adc     _CStackAddr
	sta     _CStackAddr
	bcc     L03BA
	inc     _CStackAddr+1
	jmp     L03BA
L0503:	ldx     #$00
	lda     (sp),y
	jmp     incsp2
L03BA:	jsr     _UpdateCStack
	jmp     L03B3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ DumpHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DumpHandler: near

.segment	"CODE"

	jsr     decsp1
	ldx     #$00
	lda     _DumpFrame+9
	jsr     shlax3
	jsr     pushax
L03F3:	jsr     _GetKeyUpdate
	ldy     #$02
	sta     (sp),y
	cmp     #$11
	beq     L0412
	cmp     #$2B
	beq     L03FC
	cmp     #$2D
	beq     L0400
	cmp     #$41
	beq     L040B
	cmp     #$47
	beq     L0404
	cmp     #$4F
	beq     L0408
	cmp     #$5A
	beq     L0412
	cmp     #$91
	beq     L040B
	jmp     L0504
L03FC:	jsr     ldax0sp
	clc
	adc     _DumpAddr
	sta     _DumpAddr
	txa
	adc     _DumpAddr+1
	sta     _DumpAddr+1
	jmp     L03FA
L0400:	jsr     ldax0sp
	eor     #$FF
	sec
	adc     _DumpAddr
	sta     _DumpAddr
	txa
	eor     #$FF
	adc     _DumpAddr+1
	sta     _DumpAddr+1
	jmp     L03FA
L0404:	lda     #<(_DumpAddr)
	ldx     #>(_DumpAddr)
	jsr     _InputGoto
	jmp     L03FA
L0408:	jsr     _DumpHome
	jmp     L03FA
L040B:	lda     _DumpAddr
	sec
	sbc     #$08
	sta     _DumpAddr
	bcs     L03FA
	dec     _DumpAddr+1
	jmp     L03FA
L0412:	lda     #$08
	clc
	adc     _DumpAddr
	sta     _DumpAddr
	bcc     L03FA
	inc     _DumpAddr+1
	jmp     L03FA
L0504:	ldx     #$00
	lda     (sp),y
	jmp     incsp3
L03FA:	jsr     _UpdateDump
	jmp     L03F3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ HelpHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_HelpHandler: near

.segment	"CODE"

	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	jsr     pushax
	lda     #$05
	jsr     pusha0
	lda     #$01
	jsr     _ActivateFrame
	jsr     _AnyKeyPrompt
	jsr     _cgetc
	ldy     #$00
	lda     (sp),y
	jsr     _Redraw
	ldx     #$00
	txa
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ DisplayPrompt (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DisplayPrompt: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp1
	lda     #$01
	jsr     _textcolor
	ldy     #$00
	sta     (sp),y
	lda     _ActivePrompt
	ora     _ActivePrompt+1
	beq     L0155
	lda     _PromptColor
	jsr     _textcolor
	lda     #$28
	sec
	sbc     _PromptLength
	lsr     a
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     _PromptLength
	jsr     _chlinexy
L0155:	ldy     #$02
	jsr     ldaxysp
	sta     _ActivePrompt
	stx     _ActivePrompt+1
	ldy     #$00
	lda     (sp),y
	sta     _PromptColor
	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     _strlen
	sta     _PromptLength
	lda     #$01
	jsr     _textcolor
	lda     #$28
	sec
	sbc     _PromptLength
	lsr     a
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     _cputsxy
	lda     _PromptColor
	jsr     _textcolor
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ SingleStep (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SingleStep: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	lda     _brk_pc+1
	sta     ptr1+1
	lda     _brk_pc
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$10
	beq     L044A
	cmp     #$20
	beq     L045D
	cmp     #$30
	beq     L044A
	cmp     #$40
	beq     L0458
	cmp     #$4C
	beq     L0434
	cmp     #$50
	beq     L044A
	cmp     #$60
	beq     L0455
	cmp     #$6C
	beq     L0438
	cmp     #$70
	beq     L044A
	cmp     #$90
	beq     L044A
	cmp     #$B0
	beq     L044A
	cmp     #$D0
	beq     L044A
	cmp     #$F0
	beq     L044A
	jmp     L0432
L0434:	jsr     _GetArg16
	jmp     L0505
L0438:	jsr     _GetArg16
	jsr     ldaxi
	jmp     L0505
L044A:	lda     _brk_pc
	ldx     _brk_pc+1
	iny
	jsr     ldaidx
	dey
	sta     (sp),y
	lda     (sp),y
	beq     L0432
	ldx     #$00
	lda     (sp),y
	bpl     L0453
	dex
L0453:	clc
	adc     _brk_pc
	pha
	txa
	adc     _brk_pc+1
	tax
	pla
	jsr     incax2
	jsr     _DbgSetTmpBreak
	jmp     L0432
L0455:	jsr     _SetRTSBreak
	jmp     incsp2
L0458:	lda     #$01
	jsr     _GetStack16
	jmp     L0505
L045D:	iny
	lda     (sp),y
	beq     L0432
	jsr     _GetArg16
	jmp     L0505
L0432:	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     pushax
	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _DbgDisAsmLen
	jsr     tosaddax
L0505:	jsr     _DbgSetTmpBreak
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ RedrawStatic (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_RedrawStatic: near

.segment	"CODE"

	jsr     pusha
	lda     #$FF
	sta     _ActiveFrame
	sta     _ActiveFrame+1
	lda     #$00
	jsr     _bordercolor
	lda     #$00
	jsr     _bgcolor
	jsr     _clrscr
	lda     #$00
	jsr     _cursor
	lda     #$0F
	jsr     _textcolor
	jsr     _DrawFrames
	jsr     _HelpPrompt
	ldy     #$00
	lda     (sp),y
	jsr     pusha0
	lda     #$00
	jsr     _ActivateFrame
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ Redraw (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Redraw: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	jsr     _RedrawStatic
	jsr     _UpdateAsm
	jsr     _UpdateReg
	jsr     _UpdateStack
	jsr     _UpdateCStack
	jsr     _UpdateDump
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ GetKeyUpdate (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetKeyUpdate: near

.segment	"BSS"

L047F:
	.res	1,$00

.segment	"CODE"

	jmp     L0482
L0506:	lda     L047F
	beq     L0488
	cmp     #$01
	beq     L048B
	cmp     #$02
	beq     L048E
	cmp     #$03
	beq     L0491
	jmp     L0507
L0488:	jsr     _UpdateAsm
	jmp     L0507
L048B:	jsr     _UpdateStack
	jmp     L0507
L048E:	jsr     _UpdateCStack
	jmp     L0507
L0491:	jsr     _UpdateDump
L0507:	lda     L047F
	clc
	adc     #$01
	and     #$03
	sta     L047F
L0482:	jsr     _kbhit
	tax
	beq     L0506
	jmp     _cgetc

.endproc

; ---------------------------------------------------------------
; void __near__ DrawFrame (register __near__ const struct $anon-struct-0014 *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DrawFrame: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	ldx     #$04
	jsr     regswap2
	ldy     #$0B
	jsr     subysp
	ldy     #$0B
	lda     (sp),y
	beq     L00D4
	lda     #$01
	jsr     _textcolor
	ldy     #$00
	sta     (sp),y
	lda     #$B0
	ldy     #$07
	sta     (sp),y
	lda     #$AE
	dey
	sta     (sp),y
	lda     #$AD
	dey
	sta     (sp),y
	lda     #$BD
	jmp     L0509
L00D4:	lda     #$0F
	jsr     _textcolor
	ldy     #$00
	sta     (sp),y
	lda     (regbank+4),y
	ldy     #$07
	sta     (sp),y
	ldy     #$01
	lda     (regbank+4),y
	ldy     #$06
	sta     (sp),y
	ldy     #$02
	lda     (regbank+4),y
	ldy     #$05
	sta     (sp),y
	ldy     #$03
	lda     (regbank+4),y
L0509:	ldy     #$04
	sta     (sp),y
	lda     (regbank+4),y
	dey
	sta     (sp),y
	ldy     #$05
	lda     (regbank+4),y
	ldy     #$02
	sta     (sp),y
	ldy     #$08
	lda     (regbank+4),y
	ldy     #$01
	sta     (sp),y
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     _cputcxy
	ldy     #$01
	lda     (sp),y
	jsr     _chline
	ldy     #$06
	lda     (sp),y
	jsr     _cputc
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (regbank+4),y
	jsr     _cvlinexy
	ldy     #$05
	lda     (sp),y
	jsr     _cputc
	ldy     #$01
	lda     (sp),y
	jsr     _chline
	ldy     #$04
	lda     (sp),y
	jsr     _cputc
	ldy     #$06
	lda     (regbank+4),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (regbank+4),y
	jsr     _cvlinexy
	lda     #$0F
	jsr     _textcolor
	ldy     #$0D
	lda     (regbank+4),y
	ldy     #$08
	sta     (sp),y
	ldy     #$0F
	lda     (regbank+4),y
	tax
	dey
	lda     (regbank+4),y
	ldy     #$09
	jsr     staxysp
	jmp     L0111
L010F:	ldy     #$03
	lda     (sp),y
	jsr     pusha0
	ldy     #$0C
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jsr     tosadda0
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha0
	ldy     #$0D
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     tosadda0
	jsr     pusha
	ldy     #$0C
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _cputsxy
	ldy     #$09
	ldx     #$00
	lda     #$04
	jsr     addeqysp
L0111:	ldy     #$08
	lda     (sp),y
	pha
	sec
	sbc     #$01
	sta     (sp),y
	pla
	tax
	bne     L010F
	lda     (sp,x)
	jsr     _textcolor
	ldy     #$0C
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	iny
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ DrawFrames (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DrawFrames: near

.segment	"CODE"

	jsr     decsp3
	lda     #$00
	ldy     #$02
L050B:	sta     (sp),y
	cmp     #$06
	bcs     L011C
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L050C
	inx
	clc
L050C:	adc     #<(_Frames)
	tay
	txa
	adc     #>(_Frames)
	tax
	tya
	jsr     ldaxi
	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	beq     L011D
	jsr     pushw0sp
	lda     #$00
	jsr     _DrawFrame
L011D:	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L050B
L011C:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ ActivateFrame (int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ActivateFrame: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	lda     regbank+4
	ldx     regbank+5
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	cpx     _ActiveFrame+1
	bne     L050F
	cmp     _ActiveFrame
	jeq     L012F
L050F:	ldx     _ActiveFrame+1
	bmi     L0131
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	jsr     aslax1
	clc
	adc     #<(_Frames)
	tay
	txa
	adc     #>(_Frames)
	tax
	tya
	jsr     pushw
	lda     #$00
	jsr     _DrawFrame
L0131:	ldy     #$05
	jsr     ldaxysp
	sta     _ActiveFrame
	stx     _ActiveFrame+1
	txa
	bmi     L0137
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	jsr     aslax1
	clc
	adc     #<(_Frames)
	tay
	txa
	adc     #>(_Frames)
	tax
	tya
	jsr     ldaxi
	sta     regbank+4
	stx     regbank+4+1
	ldy     #$03
	lda     (sp),y
	beq     L0141
	ldy     #$05
	lda     (regbank+4),y
	clc
	adc     #$01
	ldy     #$02
L050E:	sta     (sp),y
	lda     (sp),y
	jsr     pusha0
	ldy     #$07
	lda     (regbank+4),y
	jsr     tosicmp0
	bcs     L0141
	ldy     #$04
	lda     (regbank+4),y
	clc
	adc     #$01
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (regbank+4),y
	jsr     _cclearxy
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L050E
L0141:	lda     regbank+4
	ldx     regbank+4+1
	jsr     pushax
	lda     #$01
	jsr     _DrawFrame
L0137:	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     _DisplayPrompt
L012F:	ldy     #$00
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ HelpPrompt (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_HelpPrompt: near

.segment	"CODE"

	lda     #<(L0170)
	ldx     #>(L0170)
	jmp     _DisplayPrompt

.endproc

; ---------------------------------------------------------------
; void __near__ AnyKeyPrompt (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AnyKeyPrompt: near

.segment	"CODE"

	lda     #<(L0174)
	ldx     #>(L0174)
	jmp     _DisplayPrompt

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ IsAbortKey (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_IsAbortKey: near

.segment	"CODE"

	jsr     pusha
	ldx     #$00
	lda     (sp,x)
	cmp     #$1B
	bne     L0511
	lda     #$01
	jmp     incsp1
L0511:	lda     (sp,x)
	cmp     #$03
	bne     L0512
	lda     #$01
	jmp     incsp1
L0512:	txa
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Input (__near__ unsigned char *, __near__ unsigned char *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Input: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp8
	lda     #$00
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     #$28
	jsr     _cclearxy
	lda     #$01
	jsr     _textcolor
	ldy     #$05
	sta     (sp),y
	lda     #$00
	jsr     pusha
	lda     #$18
	jsr     pusha
	ldy     #$0E
	jsr     ldaxysp
	jsr     _cputsxy
	lda     #$0F
	jsr     _textcolor
	jsr     _wherex
	ldy     #$03
	sta     (sp),y
	lda     #$01
	jsr     _cursor
	ldy     #$04
	sta     (sp),y
	lda     #$00
	ldy     #$01
	sta     (sp),y
	iny
	sta     (sp),y
L0194:	jsr     _cgetc
	ldy     #$00
	sta     (sp),y
	ldx     #$00
	jsr     _isalnum
	stx     tmp1
	ora     tmp1
	beq     L0199
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldy     #$08
	cmp     (sp),y
	bcs     L0199
	ldy     #$02
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (sp),y
	sta     (ptr1),y
	ldy     #$02
	lda     (sp),y
	clc
	iny
	adc     (sp),y
	jsr     pusha
	lda     #$18
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _cputcxy
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0516
L0199:	ldy     #$02
	lda     (sp),y
	beq     L01A7
	ldy     #$00
	lda     (sp),y
	cmp     #$14
	bne     L051D
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$01
	sta     (sp),y
	clc
	iny
	adc     (sp),y
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     #$20
	jsr     _cputcxy
	ldy     #$02
	lda     (sp),y
	clc
	iny
	adc     (sp),y
	jsr     pusha
	lda     #$18
	jsr     _gotoxy
	jmp     L01BC
L01A7:	tay
L051D:	lda     (sp),y
	cmp     #$0D
	bne     L051B
	ldy     #$02
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	sta     ptr1
	lda     #$00
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	lda     #$01
	jmp     L051C
L051B:	lda     (sp),y
	jsr     _IsAbortKey
	tax
	beq     L01BC
	lda     #$02
L051C:	ldy     #$01
L0516:	sta     (sp),y
L01BC:	ldy     #$01
	lda     (sp),y
	jeq     L0194
	ldy     #$04
	lda     (sp),y
	jsr     _cursor
	ldy     #$05
	lda     (sp),y
	jsr     _textcolor
	jsr     _DrawFrames
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	ldy     #$06
	jsr     staxysp
	lda     #$FF
	sta     _ActiveFrame
	sta     _ActiveFrame+1
	ldy     #$09
	jsr     pushwysp
	lda     #$00
	jsr     _ActivateFrame
	ldy     #$01
	lda     (sp),y
	cmp     #$01
	jsr     booleq
	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ InputHex (__near__ unsigned char *, __near__ unsigned int *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InputHex: near

.segment	"CODE"

	jsr     pushax
	ldy     #$0A
	jsr     subysp
	ldy     #$0F
	jsr     pushwysp
	lda     #$07
	jsr     leaa0sp
	jsr     pushax
	lda     #$04
	jsr     _Input
	tax
	jeq     L01FB
	ldy     #$05
	lda     (sp),y
	ldx     #$00
	jsr     _isxdigit
	stx     tmp1
	ora     tmp1
	bne     L01D3
	tax
	jmp     L01FB
L01D3:	lda     #$05
	jsr     leaa0sp
	ldy     #$03
	jsr     staxysp
	ldx     #$00
	txa
	jsr     stax0sp
	jmp     L01E2
L01E0:	jsr     ldax0sp
	jsr     shlax4
	jsr     stax0sp
	ldy     #$02
	lda     (sp),y
	ldx     #$00
	jsr     _isdigit
	stx     tmp1
	ora     tmp1
	beq     L01EB
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$30
	jmp     L051F
L01EB:	ldy     #$02
	lda     (sp),y
	ldx     #$00
	jsr     _toupper
	ldy     #$B7
	jsr     decaxy
	ldy     #$02
L051F:	sta     (sp),y
	ldx     #$00
	jsr     addeq0sp
	ldy     #$03
	ldx     #$00
	lda     #$01
	jsr     addeqysp
L01E2:	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	ldy     #$02
	sta     (sp),y
	tax
	beq     L051E
	lda     (sp),y
	ldx     #$00
	jsr     _isxdigit
	stx     tmp1
	ora     tmp1
	bne     L01E0
L051E:	ldy     #$0B
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	jsr     ldax0sp
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	ldx     #$00
	tya
L01FB:	ldy     #$0E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ ErrorPrompt (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ErrorPrompt: near

.segment	"CODE"

	jsr     pushax
	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     _DisplayPrompt
	jsr     _cgetc
	jsr     ldax0sp
	jsr     _DisplayPrompt
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ InputGoto (__near__ unsigned int *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InputGoto: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp1
	lda     #<(L0207)
	ldx     #>(L0207)
	jsr     pushax
	ldy     #$04
	jsr     ldaxysp
	jsr     _InputHex
	ldy     #$00
	sta     (sp),y
	lda     (sp),y
	bne     L0525
	lda     #<(L020D)
	ldx     #>(L020D)
	jsr     _ErrorPrompt
L0525:	ldx     #$00
	lda     (sp,x)
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ BreakInRomError (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_BreakInRomError: near

.segment	"CODE"

	lda     #<(L0212)
	ldx     #>(L0212)
	jmp     _ErrorPrompt

.endproc

; ---------------------------------------------------------------
; void __near__ DbgSetTmpBreak (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgSetTmpBreak: near

.segment	"CODE"

	jsr     pushax
	jsr     _DbgGetBreakSlot
	jsr     pushax
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	jsr     ldaxysp
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$80
	ldy     #$03
	sta     (ptr1),y
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ DbgToggleUserBreak (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgToggleUserBreak: near

.segment	"CODE"

	jsr     pushax
	lda     regbank+4
	ldx     regbank+5
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     _DbgIsBreak
	sta     regbank+4
	stx     regbank+4+1
	lda     regbank+4
	ora     regbank+4+1
	beq     L021D
	lda     #$00
	ldy     #$03
	sta     (regbank+4),y
	dec     _DbgBreakCount
	jmp     L022D
L021D:	lda     _DbgBreakCount
	cmp     #$0A
	bcc     L0223
	lda     #<(L0226)
	ldx     #>(L0226)
	jsr     _ErrorPrompt
	jmp     L022D
L0223:	ldy     #$03
	jsr     ldaxysp
	jsr     _DbgIsRAM
	stx     tmp1
	ora     tmp1
	bne     L0229
	jsr     _BreakInRomError
	jmp     L022D
L0229:	jsr     _DbgGetBreakSlot
	sta     regbank+4
	stx     regbank+4+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	jsr     ldaxysp
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	tya
	ldy     #$03
	sta     (regbank+4),y
	inc     _DbgBreakCount
L022D:	ldy     #$00
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ DbgResetTmpBreaks (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgResetTmpBreaks: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(_DbgBreaks)
	ldx     #>(_DbgBreaks)
	jsr     pushax
	lda     #$00
	ldy     #$02
L0527:	sta     (sp),y
	cmp     #$0A
	bcs     L0238
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	cmp     #$80
	bne     L023F
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$03
	sta     (ptr1),y
L023F:	ldx     #$00
	lda     #$04
	jsr     addeq0sp
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0527
L0238:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ DbgTmpBreaksOk (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgTmpBreaksOk: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(_DbgBreaks)
	ldx     #>(_DbgBreaks)
	jsr     pushax
	lda     #$00
	ldy     #$02
L0528:	sta     (sp),y
	ldx     #$00
	lda     (sp),y
	cmp     #$0A
	bcs     L052A
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	cmp     #$80
	bne     L024E
	jsr     ldax0sp
	jsr     ldaxi
	jsr     _DbgIsRAM
	stx     tmp1
	ora     tmp1
	bne     L024E
	jsr     _BreakInRomError
	jsr     _DbgResetTmpBreaks
	ldx     #$00
	txa
	jmp     incsp3
L024E:	ldx     #$00
	lda     #$04
	jsr     addeq0sp
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0528
L052A:	lda     #$01
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ AsmBack (unsigned int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmBack: near

.segment	"CODE"

	jsr     pusha
	ldy     #$43
	jsr     subysp
	lda     #$06
	jsr     pusha0
L025B:	lda     #$00
	ldy     #$02
	sta     (sp),y
	ldy     #$49
	jsr     pushwysp
	ldy     #$47
	ldx     #$00
	lda     (sp),y
	jsr     mulax3
	jsr     tossubax
	sec
	ldy     #$00
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	tax
	pla
	ldy     #$43
	jsr     staxysp
L0264:	ldy     #$44
	jsr     ldaxysp
	jsr     _DbgDisAsmLen
	ldy     #$43
	jsr     addeqysp
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L052E
	inx
	clc
L052E:	adc     #$03
	bcc     L026D
	inx
	clc
L026D:	adc     sp
	sta     ptr1
	txa
	adc     sp+1
	sta     ptr1+1
	ldy     #$44
	jsr     ldaxysp
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	iny
	lda     (sp),y
	clc
	adc     #$01
	and     #$1F
	sta     (sp),y
	ldy     #$44
	jsr     ldaxysp
	ldy     #$46
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bcc     L0264
	ldy     #$44
	jsr     ldaxysp
	ldy     #$46
	cmp     (sp),y
	bne     L0530
	txa
	iny
	cmp     (sp),y
	beq     L0275
L0530:	ldy     #$01
	lda     (sp),y
	bne     L0532
	dey
	lda     (sp),y
	cmp     #$0C
	bne     L0532
L0275:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	sec
	ldy     #$45
	sbc     (sp),y
	sec
	sbc     #$01
	and     #$1F
	asl     a
	bcc     L052F
	inx
	clc
L052F:	adc     #$03
	bcc     L027B
	inx
	clc
L027B:	adc     sp
	tay
	txa
	adc     sp+1
	tax
	tya
	jsr     ldaxi
	jmp     L025C
L0532:	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	jmp     L025B
L025C:	ldy     #$48
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateAsm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateAsm: near

.segment	"CODE"

	ldy     #$2A
	jsr     subysp
	lda     _AsmFrame+8
	jsr     pusha
	lda     _AsmFrame+4
	clc
	adc     #$01
	jsr     pusha
	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     pushax
	lda     #$02
	jsr     _AsmBack
	jsr     pushax
	lda     _AsmFrame+5
	clc
	adc     #$01
	ldy     #$04
L0535:	sta     (sp),y
	cmp     _AsmFrame+7
	jcs     L0286
	jsr     pushw0sp
	lda     #$08
	jsr     leaa0sp
	jsr     pushax
	ldy     #$07
	lda     (sp),y
	jsr     _DbgDisAsm
	ldy     #$05
	sta     (sp),y
	jsr     ldax0sp
	cpx     _brk_pc+1
	bne     L0292
	cmp     _brk_pc
	bne     L0292
	lda     #$2D
	ldy     #$0A
	sta     (sp),y
	lda     #$3E
	iny
	sta     (sp),y
L0292:	jsr     ldax0sp
	jsr     _DbgIsBreak
	stx     tmp1
	ora     tmp1
	beq     L029A
	lda     #$2A
	ldy     #$0B
	sta     (sp),y
L029A:	jsr     ldax0sp
	cpx     _AsmAddr+1
	bne     L02A0
	cmp     _AsmAddr
	bne     L02A0
	lda     #$01
	jsr     _revers
	lda     #$01
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$08
	jsr     leaa0sp
	jsr     _cputsxy
	lda     #$00
	jsr     _revers
	jmp     L02AA
L02A0:	lda     #$01
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$08
	jsr     leaa0sp
	jsr     _cputsxy
L02AA:	ldy     #$05
	lda     (sp),y
	ldx     #$00
	jsr     addeq0sp
	ldy     #$04
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0535
L0286:	jsr     ldax0sp
	ldy     #$2E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ AsmArg16 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmArg16: near

.segment	"CODE"

	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     incax1
	ldy     #$01
	jmp     ldaxidx

.endproc

; ---------------------------------------------------------------
; void __near__ AsmFollow (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmFollow: near

.segment	"CODE"

	lda     _AsmAddr+1
	sta     ptr1+1
	lda     _AsmAddr
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$10
	beq     L02C4
	cmp     #$20
	beq     L02BA
	cmp     #$30
	beq     L02C4
	cmp     #$40
	beq     L053A
	cmp     #$4C
	beq     L02BA
	cmp     #$50
	beq     L02C4
	cmp     #$60
	beq     L0539
	cmp     #$6C
	beq     L02C0
	cmp     #$70
	beq     L02C4
	cmp     #$90
	beq     L02C4
	cmp     #$B0
	beq     L02C4
	cmp     #$D0
	beq     L02C4
	cmp     #$F0
	beq     L02C4
	rts
L02BA:	jsr     _AsmArg16
	jmp     L053B
L02C0:	jsr     _AsmArg16
	jmp     L0537
L02C4:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     incax2
	jsr     pushax
	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     incax1
	ldy     #$00
	jsr     ldaidx
	jsr     tosaddax
	jmp     L053B
L0539:	ldx     #$01
	txa
	clc
	adc     _DbgSP
	bcc     L0536
	inx
L0536:	jsr     ldaxi
	jsr     incax1
	jmp     L053B
L053A:	ldx     #$01
	lda     #$02
	clc
	adc     _DbgSP
	bcc     L0537
	inx
L0537:	jsr     ldaxi
L053B:	sta     _AsmAddr
	stx     _AsmAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ AsmHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmHome: near

.segment	"CODE"

	lda     _brk_pc+1
	sta     _AsmAddr+1
	lda     _brk_pc
	sta     _AsmAddr
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitAsm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitAsm: near

.segment	"CODE"

	jsr     _AsmHome
	jmp     _UpdateAsm

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateReg (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateReg: near

.segment	"CODE"

	lda     _RegFrame+4
	clc
	adc     #$05
	jsr     pusha
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$02
	jsr     pusha
	lda     _RegFrame+5
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _cputhex16
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_sr
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_a
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_x
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_y
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgSP
	jsr     _cputhex8
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgCS
	ldx     _DbgCS+1
	jsr     _cputhex16
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgHI
	ldx     _DbgHI+1
	jsr     _cputhex16
	ldx     #$00
	txa
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ InitReg (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitReg: near

.segment	"CODE"

	jmp     _UpdateReg

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateStack: near

.segment	"CODE"

	lda     _StackAddr
	jsr     pusha
	lda     _StackFrame+4
	clc
	adc     #$01
	jsr     pusha
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$06
	jsr     pusha
	jsr     decsp1
	lda     _StackFrame+7
	sec
	sbc     #$01
	ldy     #$00
L053F:	sta     (sp),y
	ldx     #$00
	lda     (sp),y
	sec
	sbc     _StackFrame+5
	sta     tmp1
	lda     tmp1
	beq     L0357
	bcc     L0357
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldy     #$03
	lda     (sp),y
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldx     #$01
	lda     #$00
	clc
	ldy     #$03
	adc     (sp),y
	bcc     L053D
	inx
L053D:	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _cputhex8
	ldy     #$03
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldy     #$00
	lda     (sp),y
	sec
	sbc     #$01
	jmp     L053F
L0357:	ldy     #$03
	lda     (sp),y
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ StackHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_StackHome: near

.segment	"CODE"

	lda     _DbgSP
	clc
	adc     #$01
	sta     _StackAddr
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitStack: near

.segment	"CODE"

	jsr     _StackHome
	jmp     _UpdateStack

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateCStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateCStack: near

.segment	"CODE"

	lda     _CStackAddr
	ldx     _CStackAddr+1
	jsr     pushax
	lda     _CStackFrame+4
	clc
	adc     #$05
	jsr     pusha
	jsr     decsp1
	lda     _CStackFrame+7
	sec
	sbc     #$01
	ldy     #$00
L0541:	sta     (sp),y
	sec
	sbc     _CStackFrame+5
	sta     tmp1
	lda     tmp1
	beq     L0542
	bcc     L0542
	iny
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldy     #$03
	jsr     ldaxysp
	jsr     ldaxi
	jsr     _cputhex16
	ldy     #$02
	ldx     #$00
	tya
	jsr     addeqysp
	ldy     #$00
	lda     (sp),y
	sec
	sbc     #$01
	jmp     L0541
L0542:	lda     _CStackFrame+4
	clc
	adc     #$01
	jsr     pusha
	lda     _CStackFrame+7
	sec
	sbc     #$01
	jsr     pusha
	lda     #<(L03A8)
	ldx     #>(L03A8)
	jsr     _cputsxy
	ldy     #$03
	jsr     ldaxysp
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ CStackHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_CStackHome: near

.segment	"CODE"

	lda     _DbgCS+1
	sta     _CStackAddr+1
	lda     _DbgCS
	sta     _CStackAddr
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitCStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitCStack: near

.segment	"CODE"

	jsr     _CStackHome
	jmp     _UpdateCStack

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateDump (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateDump: near

.segment	"CODE"

	ldy     #$29
	jsr     subysp
	lda     _DumpAddr
	ldx     _DumpAddr+1
	jsr     pushax
	lda     _DumpFrame+4
	clc
	adc     #$01
	jsr     pusha
	ldy     #$04
	jsr     pushwysp
	lda     _DumpFrame+5
	clc
	adc     #$01
	ldy     #$05
L0543:	sta     (sp),y
	cmp     _DumpFrame+7
	bcs     L03DD
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	jsr     pushwysp
	lda     #$0A
	jsr     leaa0sp
	jsr     pushax
	lda     #$08
	jsr     pusha
	jsr     _DbgMemDump
	jsr     _cputsxy
	ldy     #$03
	ldx     #$00
	lda     #$08
	jsr     addeqysp
	ldy     #$05
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0543
L03DD:	dey
	jsr     ldaxysp
	ldy     #$2E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ DumpHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DumpHome: near

.segment	"CODE"

	lda     #$00
	sta     _DumpAddr
	sta     _DumpAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ GetArg16 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetArg16: near

.segment	"CODE"

	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     incax1
	ldy     #$01
	jmp     ldaxidx

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ GetStack16 (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetStack16: near

.segment	"CODE"

	jsr     pusha
	ldx     #$00
	lda     (sp,x)
	clc
	adc     _DbgSP
	bcc     L0544
	inx
L0544:	sta     ptr1
	stx     ptr1+1
	ldx     #$01
	txa
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ SetRTSBreak (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SetRTSBreak: near

.segment	"CODE"

	lda     #$00
	jsr     _GetStack16
	jsr     incax1
	jmp     _DbgSetTmpBreak

.endproc

; ---------------------------------------------------------------
; void __near__ DbgEntry (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgEntry: near

.segment	"DATA"

L0498:
	.byte	$01

.segment	"CODE"

	jsr     decsp2
	lda     L0498
	beq     L049A
	lda     #$00
	sta     L0498
	jsr     _RedrawStatic
	jsr     _InitAsm
	jsr     _InitReg
	jsr     _InitStack
	jsr     _InitCStack
	jsr     _UpdateDump
L049A:	jsr     _AsmHome
	jsr     _UpdateReg
	jsr     _StackHome
	jsr     _CStackHome
	lda     #$00
	tay
	sta     (sp),y
	jmp     L0549
L04AB:	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	jsr     aslax1
	clc
	adc     #<(_Frames)
	tay
	txa
	adc     #>(_Frames)
	tax
	tya
	jsr     ldaxi
	ldy     #$0C
	jsr     ldaxidx
	jsr     callax
	ldy     #$01
	sta     (sp),y
	ldx     #$00
	lda     (sp),y
	jeq     L0548
	cmp     #$0D
	jeq     L04E3
	cmp     #$20
	jeq     L04D9
	cmp     #$31
	beq     L0547
	cmp     #$32
	beq     L0547
	cmp     #$33
	beq     L0547
	cmp     #$34
	beq     L0547
	cmp     #$35
	beq     L0547
	cmp     #$3F
	beq     L04C3
	cmp     #$43
	jeq     L0548
	cmp     #$48
	beq     L04CF
	cmp     #$51
	jeq     L04FD
	cmp     #$52
	jeq     L04F9
	cmp     #$53
	jeq     L04F3
	cmp     #$55
	beq     L04C8
	cmp     #$E0
	beq     L04C3
	cmp     #$E2
	beq     L04C8
	cmp     #$E3
	beq     L04CF
	cmp     #$E6
	beq     L04D9
	cmp     #$E7
	beq     L04E3
	jmp     L04B4
L0547:	lda     (sp),y
	ldy     #$31
	jsr     decaxy
	jsr     pushax
	lda     #$00
	jsr     _ActivateFrame
	jmp     L04B4
L04C3:	jsr     _HelpHandler
	jmp     L04B4
L04C8:	jsr     _SetRTSBreak
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L0549
L04CF:	lda     _brk_pc
	ldx     _brk_pc+1
	cpx     _AsmAddr+1
	bne     L054A
	cmp     _AsmAddr
	beq     L04B4
L054A:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     _DbgSetTmpBreak
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L0549
L04D9:	tya
	jsr     _SingleStep
	jsr     _DbgTmpBreaksOk
	tax
	beq     L04B4
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L0549
L04E3:	txa
	jsr     _SingleStep
	jsr     _DbgTmpBreaksOk
	tax
	beq     L04B4
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L0549
L0548:	tya
	dey
	sta     (sp),y
	jmp     L0549
L04F3:	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _DbgDisAsmLen
	clc
	adc     _brk_pc
	sta     _brk_pc
	txa
	adc     _brk_pc+1
	sta     _brk_pc+1
	jsr     _InitAsm
	jmp     L04B4
L04F9:	lda     _ActiveFrame
	jsr     _Redraw
	jmp     L04B4
L04FD:	jsr     _clrscr
	ldx     #$00
	lda     #$01
	jsr     _exit
L04B4:	ldy     #$00
L0549:	lda     (sp),y
	jeq     L04AB
	jmp     incsp2

.endproc

