;
; File generated by cc65 v 2.17 - Git 582aa41
;
	.fopt		compiler,"cc65 v 2.17 - Git 582aa41"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_cbm_k_load
	.import		_cbm_k_setlfs
	.import		_cbm_k_setnam
	.export		_cbm_load

; ---------------------------------------------------------------
; unsigned int __near__ __fastcall__ cbm_load (__near__ const unsigned char *, unsigned char, __near__ void *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cbm_load: near

.segment	"CODE"

	jsr     pushax
	lda     #$00
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	jsr     ldaxysp
	cpx     #$00
	bne     L0008
	cmp     #$00
L0008:	jsr     booleq
	jsr     _cbm_k_setlfs
	ldy     #$04
	jsr     ldaxysp
	jsr     _cbm_k_setnam
	lda     #$00
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	jsr     _cbm_k_load
	sec
	ldy     #$00
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	tax
	pla
	jmp     incsp5

.endproc

