;
; File generated by cc65 v 2.17 - Git 582aa41
;
	.fopt		compiler,"cc65 v 2.17 - Git 582aa41"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_stderr
	.import		_fprintf
	.export		__poserror
	.import		__stroserror
	.import		__oserror

.segment	"RODATA"

L0008:
	.byte	$25,$53,$3A,$20,$25,$53,$0D,$00
L000F	:=	L0008+4

; ---------------------------------------------------------------
; void __near__ __fastcall__ _poserror (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__poserror: near

.segment	"CODE"

	jsr     pushax
	lda     __oserror
	jsr     __stroserror
	jsr     pushax
	ldy     #$03
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L0004
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(L0008)
	ldx     #>(L0008)
	jsr     pushax
	ldy     #$09
	jsr     pushwysp
	ldy     #$09
	jsr     pushwysp
	ldy     #$08
	jmp     L0012
L0004:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(L000F)
	ldx     #>(L000F)
	jsr     pushax
	ldy     #$07
	jsr     pushwysp
	ldy     #$06
L0012:	jsr     _fprintf
	jmp     incsp4

.endproc

