;
; File generated by cc65 v 2.17 - Git 582aa41
;
	.fopt		compiler,"cc65 v 2.17 - Git 582aa41"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_exit
	.import		_ExitTurbo
	.import		_SetPattern
	.import		_Rectangle
	.import		_FrameRectangle
	.import		_PutString
	.import		_PutDecimal
	.import		_DlgBoxOk
	.export		__afailed

.segment	"RODATA"

L003E:
	.byte	$50,$52,$4F,$47,$52,$41,$4D,$20,$54,$45,$52,$4D,$49,$4E,$41,$54
	.byte	$45,$44,$1B,$00
L003C:
	.byte	$18,$41,$53,$53,$45,$52,$54,$49,$4F,$4E,$20,$46,$41,$49,$4C,$45
	.byte	$44,$00
L002E:
	.byte	$18,$20,$20,$6C,$69,$6E,$65,$3A,$20,$00
L0023:
	.byte	$18,$66,$69,$6C,$65,$3A,$20,$00

; ---------------------------------------------------------------
; void __near__ _afailed (__near__ unsigned char *, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__afailed: near

.segment	"CODE"

	jsr     pushax
	jsr     _ExitTurbo
	lda     #$00
	sta     $0006
	tax
	sta     $0008
	sta     $0008+1
	lda     #$0F
	sta     $0007
	lda     #$96
	sta     $000A
	stx     $000A+1
	lda     #$C0
	sta     $002F
	txa
	jsr     _SetPattern
	jsr     _Rectangle
	lda     #$FF
	jsr     _FrameRectangle
	lda     #<(L0023)
	ldx     #>(L0023)
	jsr     pushax
	lda     #$0A
	jsr     pusha
	ldx     #$00
	jsr     _PutString
	ldy     #$05
	jsr     pushwysp
	lda     #$0A
	jsr     pusha
	lda     $0018
	ldx     $0018+1
	jsr     _PutString
	lda     #<(L002E)
	ldx     #>(L002E)
	jsr     pushax
	lda     #$0A
	jsr     pusha
	lda     $0018
	ldx     $0018+1
	jsr     _PutString
	lda     #$00
	jsr     pusha
	ldy     #$04
	jsr     pushwysp
	lda     #$0A
	jsr     pusha
	lda     $0018
	ldx     $0018+1
	jsr     _PutDecimal
	lda     #<(L003C)
	ldx     #>(L003C)
	jsr     pushax
	lda     #<(L003E)
	ldx     #>(L003E)
	jsr     _DlgBoxOk
	ldx     #$00
	lda     #$02
	jsr     _exit
	jmp     incsp4

.endproc

