;
; File generated by cc65 v 2.17 - Git 582aa41
;
	.fopt		compiler,"cc65 v 2.17 - Git 582aa41"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		__clocks_per_sec
	.import		_clock
	.export		_sleep

; ---------------------------------------------------------------
; unsigned int __near__ __fastcall__ sleep (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sleep: near

.segment	"CODE"

	jsr     pushax
	jsr     _clock
	jsr     pusheax
	ldy     #$05
	jsr     ldaxysp
	jsr     axulong
	jsr     pusheax
	jsr     __clocks_per_sec
	jsr     axulong
	jsr     tosumuleax
	jsr     tosaddeax
	jsr     pusheax
L0006:	jsr     ldeax0sp
	jsr     pusheax
	jsr     _clock
	jsr     tossubeax
	jsr     pusheax
	ldx     #$00
	stx     sreg
	stx     sreg+1
	lda     #$01
	jsr     tosgeeax
	bne     L0006
	ldx     #$00
	txa
	jmp     incsp6

.endproc

