;
; File generated by cc65 v 2.17 - Git 582aa41
;
	.fopt		compiler,"cc65 v 2.17 - Git 582aa41"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_exit
	.import		_strlen
	.import		_clrscr
	.import		_kbhit
	.import		_gotoxy
	.import		_wherex
	.import		_cputc
	.import		_cputcxy
	.import		_cputsxy
	.import		_cgetc
	.import		_cursor
	.import		_revers
	.import		_chline
	.import		_chlinexy
	.import		_cvlinexy
	.import		_cclearxy
	.import		_cputhex8
	.import		_cputhex16
	.import		_isalnum
	.import		_isdigit
	.import		_isxdigit
	.import		_toupper
	.import		_brk_a
	.import		_brk_x
	.import		_brk_y
	.import		_brk_sr
	.import		_brk_pc
	.import		_DbgDisAsm
	.import		_DbgDisAsmLen
	.import		_DbgIsRAM
	.import		_DbgMemDump
	.import		_DbgSP
	.import		_DbgCS
	.import		_DbgHI
	.export		_DbgBreakCount
	.export		_DbgBreaks
	.import		_DbgGetBreakSlot
	.import		_DbgIsBreak
	.export		_DbgEntry

.segment	"DATA"

_ActiveFrame:
	.word	$FFFF
_ActivePrompt:
	.word	$0000
_DbgBreakCount:
	.byte	$00

.segment	"RODATA"

_RegText:
	.byte	$01
	.byte	$00
	.addr	L0004
	.byte	$01
	.byte	$01
	.addr	L0008
	.byte	$01
	.byte	$02
	.addr	L000C
	.byte	$01
	.byte	$03
	.addr	L0010
	.byte	$01
	.byte	$04
	.addr	L0014
	.byte	$01
	.byte	$05
	.addr	L0018
	.byte	$01
	.byte	$06
	.addr	L001C
	.byte	$01
	.byte	$07
	.addr	L0020
_HelpText:
	.byte	$01
	.byte	$00
	.addr	L0024
	.byte	$01
	.byte	$01
	.addr	L0028
	.byte	$01
	.byte	$02
	.addr	L002C
	.byte	$01
	.byte	$03
	.addr	L0030
	.byte	$01
	.byte	$04
	.addr	L0034
	.byte	$01
	.byte	$05
	.addr	L0038
	.byte	$01
	.byte	$06
	.addr	L003C
	.byte	$01
	.byte	$07
	.addr	L0040
	.byte	$01
	.byte	$08
	.addr	L0044
	.byte	$01
	.byte	$09
	.addr	L0048
	.byte	$01
	.byte	$0A
	.addr	L004C
	.byte	$01
	.byte	$0B
	.addr	L0050
	.byte	$01
	.byte	$0C
	.addr	L0054
	.byte	$01
	.byte	$0D
	.addr	L0058
	.byte	$01
	.byte	$0E
	.addr	L005C
	.byte	$01
	.byte	$0F
	.addr	L0060
	.byte	$01
	.byte	$10
	.addr	L0064
	.byte	$01
	.byte	$11
	.addr	L0068
_AsmFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$00
	.byte	$00
	.byte	$1E
	.byte	$0F
	.byte	$1D
	.byte	$0E
	.byte	$01
	.addr	_AsmHandler
	.byte	$00
	.word	$0000
_RegFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$1E
	.byte	$00
	.byte	$27
	.byte	$09
	.byte	$08
	.byte	$08
	.byte	$01
	.addr	_RegHandler
	.byte	$08
	.addr	_RegText
_StackFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$1E
	.byte	$09
	.byte	$27
	.byte	$0F
	.byte	$08
	.byte	$05
	.byte	$01
	.addr	_StackHandler
	.byte	$00
	.word	$0000
_CStackFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$1E
	.byte	$0F
	.byte	$27
	.byte	$18
	.byte	$08
	.byte	$08
	.byte	$01
	.addr	_CStackHandler
	.byte	$00
	.word	$0000
_DumpFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$00
	.byte	$0F
	.byte	$1E
	.byte	$18
	.byte	$1D
	.byte	$08
	.byte	$01
	.addr	_DumpHandler
	.byte	$00
	.word	$0000
_HelpFrame:
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$2B
	.byte	$00
	.byte	$00
	.byte	$27
	.byte	$18
	.byte	$26
	.byte	$17
	.byte	$00
	.addr	_HelpHandler
	.byte	$12
	.addr	_HelpText
_Frames:
	.addr	_AsmFrame
	.addr	_RegFrame
	.addr	_StackFrame
	.addr	_CStackFrame
	.addr	_DumpFrame
	.addr	_HelpFrame
L002C:
	.byte	$46,$33,$2C,$20,$75,$20,$20,$20,$20,$20,$52,$75,$6E,$20,$75,$6E
	.byte	$74,$69,$6C,$20,$73,$75,$62,$72,$6F,$75,$74,$69,$6E,$65,$20,$72
	.byte	$65,$74,$75,$72,$6E,$73,$00
L01FE:
	.byte	$43,$61,$6E,$6E,$6F,$74,$20,$73,$65,$74,$20,$62,$72,$65,$61,$6B
	.byte	$70,$6F,$69,$6E,$74,$20,$2D,$20,$70,$72,$65,$73,$73,$20,$61,$20
	.byte	$6B,$65,$79,$00
L0212:
	.byte	$54,$6F,$6F,$20,$6D,$61,$6E,$79,$20,$62,$72,$65,$61,$6B,$70,$6F
	.byte	$69,$6E,$74,$73,$20,$2D,$20,$70,$72,$65,$73,$73,$20,$61,$20,$6B
	.byte	$65,$79,$00
L0068:
	.byte	$73,$20,$20,$20,$20,$20,$20,$20,$20,$20,$53,$6B,$69,$70,$20,$6E
	.byte	$65,$78,$74,$20,$69,$6E,$73,$74,$72,$75,$63,$74,$69,$6F,$6E,$00
L003C:
	.byte	$31,$2D,$35,$20,$20,$20,$20,$20,$20,$20,$53,$65,$6C,$65,$63,$74
	.byte	$20,$61,$63,$74,$69,$76,$65,$20,$77,$69,$6E,$64,$6F,$77,$00
L005C:
	.byte	$70,$20,$20,$20,$20,$20,$20,$20,$20,$20,$55,$73,$65,$20,$61,$73
	.byte	$20,$6E,$65,$77,$20,$50,$43,$20,$76,$61,$6C,$75,$65,$00
L0054:
	.byte	$66,$20,$20,$20,$20,$20,$20,$20,$20,$20,$46,$6F,$6C,$6C,$6F,$77
	.byte	$20,$69,$6E,$73,$74,$72,$75,$63,$74,$69,$6F,$6E,$00
L0028:
	.byte	$46,$32,$2C,$20,$74,$20,$20,$20,$20,$20,$54,$6F,$67,$67,$6C,$65
	.byte	$20,$62,$72,$65,$61,$6B,$70,$6F,$69,$6E,$74,$00
L01F9:
	.byte	$49,$6E,$76,$61,$6C,$69,$64,$20,$69,$6E,$70,$75,$74,$20,$2D,$20
	.byte	$70,$72,$65,$73,$73,$20,$61,$20,$6B,$65,$79,$00
L0167:
	.byte	$50,$72,$65,$73,$73,$20,$61,$6E,$79,$20,$6B,$65,$79,$20,$74,$6F
	.byte	$20,$63,$6F,$6E,$74,$69,$6E,$75,$65,$00
L0030:
	.byte	$46,$34,$2C,$20,$68,$20,$20,$20,$20,$20,$52,$75,$6E,$20,$74,$6F
	.byte	$20,$63,$75,$72,$73,$6F,$72,$00
L0064:
	.byte	$72,$20,$20,$20,$20,$20,$20,$20,$20,$20,$52,$65,$64,$72,$61,$77
	.byte	$20,$73,$63,$72,$65,$65,$6E,$00
L004C:
	.byte	$61,$2F,$7A,$20,$20,$20,$20,$20,$20,$20,$4D,$6F,$76,$65,$20,$75
	.byte	$70,$2F,$64,$6F,$77,$6E,$00
L0048:
	.byte	$43,$75,$72,$73,$6F,$72,$20,$20,$20,$20,$4D,$6F,$76,$65,$20,$75
	.byte	$70,$2F,$64,$6F,$77,$6E,$00
L0058:
	.byte	$6F,$20,$20,$20,$20,$20,$20,$20,$20,$20,$47,$6F,$74,$6F,$20,$6F
	.byte	$72,$69,$67,$69,$6E,$00
L0034:
	.byte	$46,$37,$2C,$20,$73,$70,$61,$63,$65,$20,$53,$74,$65,$70,$20,$69
	.byte	$6E,$74,$6F,$00
L0038:
	.byte	$46,$38,$2C,$20,$65,$6E,$74,$65,$72,$20,$53,$74,$65,$70,$20,$6F
	.byte	$76,$65,$72,$00
L0040:
	.byte	$2B,$20,$20,$20,$20,$20,$20,$20,$20,$20,$50,$61,$67,$65,$20,$64
	.byte	$6F,$77,$6E,$00
L0050:
	.byte	$63,$20,$20,$20,$20,$20,$20,$20,$20,$20,$43,$6F,$6E,$74,$69,$6E
	.byte	$75,$65,$00
L0044:
	.byte	$2D,$20,$20,$20,$20,$20,$20,$20,$20,$20,$50,$61,$67,$65,$20,$75
	.byte	$70,$00
L0163:
	.byte	$50,$72,$65,$73,$73,$20,$46,$31,$20,$66,$6F,$72,$20,$68,$65,$6C
	.byte	$70,$00
L0060:
	.byte	$71,$20,$20,$20,$20,$20,$20,$20,$20,$20,$51,$75,$69,$74,$00
L0024:
	.byte	$46,$31,$2C,$20,$3F,$20,$20,$20,$20,$20,$48,$65,$6C,$70,$00
L01F3:
	.byte	$47,$6F,$74,$6F,$3A,$20,$00
L0008:
	.byte	$53,$52,$00
L001C:
	.byte	$43,$53,$00
L0020:
	.byte	$48,$49,$00
L0018:
	.byte	$53,$50,$00
L038A:
	.byte	$2D,$3E,$00
L0004:
	.byte	$50,$43,$00
L0010:
	.byte	$58,$00
L000C:
	.byte	$41,$00
L0014:
	.byte	$59,$00

.segment	"BSS"

_AsmAddr:
	.res	2,$00
_DumpAddr:
	.res	2,$00
_CStackAddr:
	.res	2,$00
_StackAddr:
	.res	1,$00
_PromptColor:
	.res	1,$00
_PromptLength:
	.res	1,$00
_DbgBreaks:
	.res	48,$00

; ---------------------------------------------------------------
; unsigned char __near__ AsmHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmHandler: near

.segment	"CODE"

	jsr     decsp3
L02D4:	jsr     _UpdateAsm
	jsr     stax0sp
	jsr     _GetKeyUpdate
	ldy     #$02
	sta     (sp),y
	cmp     #$2B
	beq     L02DF
	cmp     #$2D
	beq     L02E3
	cmp     #$61
	beq     L02FB
	cmp     #$66
	beq     L02ED
	cmp     #$67
	beq     L02F0
	cmp     #$6F
	beq     L02F4
	cmp     #$70
	beq     L02F7
	cmp     #$74
	beq     L02E9
	cmp     #$7A
	beq     L0301
	jmp     L04CE
L02DF:	jsr     ldax0sp
	sta     _AsmAddr
	stx     _AsmAddr+1
	jmp     L02D4
L02E3:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     pushax
	lda     _AsmFrame+9
	jsr     _AsmBack
	sta     _AsmAddr
	stx     _AsmAddr+1
	jmp     L02D4
L02E9:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     _DbgToggleUserBreak
	jmp     L02D4
L02ED:	jsr     _AsmFollow
	jmp     L02D4
L02F0:	lda     #<(_AsmAddr)
	ldx     #>(_AsmAddr)
	jsr     _InputGoto
	jmp     L02D4
L02F4:	jsr     _AsmHome
	jmp     L02D4
L02F7:	lda     _AsmAddr+1
	sta     _brk_pc+1
	lda     _AsmAddr
	sta     _brk_pc
	jmp     L02D4
L02FB:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     pushax
	lda     #$01
	jsr     _AsmBack
	sta     _AsmAddr
	stx     _AsmAddr+1
	jmp     L02D4
L0301:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     _DbgDisAsmLen
	clc
	adc     _AsmAddr
	sta     _AsmAddr
	txa
	adc     _AsmAddr+1
	sta     _AsmAddr+1
	jmp     L02D4
L04CE:	ldx     #$00
	lda     (sp),y
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ RegHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_RegHandler: near

.segment	"CODE"

	jmp     _GetKeyUpdate

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ StackHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_StackHandler: near

.segment	"CODE"

	jsr     decsp1
	lda     _StackFrame+9
	jsr     pusha
L0359:	jsr     _GetKeyUpdate
	ldy     #$01
	sta     (sp),y
	cmp     #$2B
	beq     L0362
	cmp     #$2D
	beq     L0366
	cmp     #$61
	beq     L036D
	cmp     #$6F
	beq     L036A
	cmp     #$7A
	beq     L0370
	jmp     L04CF
L0362:	dey
	lda     (sp),y
	clc
	adc     _StackAddr
	sta     _StackAddr
	jmp     L0360
L0366:	dey
	lda     (sp),y
	eor     #$FF
	sec
	adc     _StackAddr
	sta     _StackAddr
	jmp     L0360
L036A:	jsr     _StackHome
	jmp     L0360
L036D:	dec     _StackAddr
	jmp     L0360
L0370:	inc     _StackAddr
	jmp     L0360
L04CF:	ldx     #$00
	lda     (sp),y
	jmp     incsp2
L0360:	jsr     _UpdateStack
	jmp     L0359

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ CStackHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_CStackHandler: near

.segment	"CODE"

	jsr     decsp1
	lda     _CStackFrame+9
	asl     a
	jsr     pusha
L0395:	jsr     _GetKeyUpdate
	ldy     #$01
	sta     (sp),y
	cmp     #$2B
	beq     L039E
	cmp     #$2D
	beq     L03A2
	cmp     #$61
	beq     L03A9
	cmp     #$6F
	beq     L03A6
	cmp     #$7A
	beq     L03AE
	jmp     L04D0
L039E:	dey
	lda     (sp),y
	clc
	adc     _CStackAddr
	sta     _CStackAddr
	tya
	adc     _CStackAddr+1
	sta     _CStackAddr+1
	jmp     L039C
L03A2:	dey
	lda     (sp),y
	eor     #$FF
	sec
	adc     _CStackAddr
	sta     _CStackAddr
	lda     #$FF
	adc     _CStackAddr+1
	sta     _CStackAddr+1
	jmp     L039C
L03A6:	jsr     _CStackHome
	jmp     L039C
L03A9:	lda     _CStackAddr
	sec
	sbc     #$02
	sta     _CStackAddr
	bcs     L039C
	dec     _CStackAddr+1
	jmp     L039C
L03AE:	lda     #$02
	clc
	adc     _CStackAddr
	sta     _CStackAddr
	bcc     L039C
	inc     _CStackAddr+1
	jmp     L039C
L04D0:	ldx     #$00
	lda     (sp),y
	jmp     incsp2
L039C:	jsr     _UpdateCStack
	jmp     L0395

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ DumpHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DumpHandler: near

.segment	"CODE"

	jsr     decsp1
	ldx     #$00
	lda     _DumpFrame+9
	jsr     shlax3
	jsr     pushax
L03D1:	jsr     _GetKeyUpdate
	ldy     #$02
	sta     (sp),y
	cmp     #$2B
	beq     L03DA
	cmp     #$2D
	beq     L03DE
	cmp     #$61
	beq     L03E9
	cmp     #$67
	beq     L03E2
	cmp     #$6F
	beq     L03E6
	cmp     #$7A
	beq     L03EE
	jmp     L04D1
L03DA:	jsr     ldax0sp
	clc
	adc     _DumpAddr
	sta     _DumpAddr
	txa
	adc     _DumpAddr+1
	sta     _DumpAddr+1
	jmp     L03D8
L03DE:	jsr     ldax0sp
	eor     #$FF
	sec
	adc     _DumpAddr
	sta     _DumpAddr
	txa
	eor     #$FF
	adc     _DumpAddr+1
	sta     _DumpAddr+1
	jmp     L03D8
L03E2:	lda     #<(_DumpAddr)
	ldx     #>(_DumpAddr)
	jsr     _InputGoto
	jmp     L03D8
L03E6:	jsr     _DumpHome
	jmp     L03D8
L03E9:	lda     _DumpAddr
	sec
	sbc     #$08
	sta     _DumpAddr
	bcs     L03D8
	dec     _DumpAddr+1
	jmp     L03D8
L03EE:	lda     #$08
	clc
	adc     _DumpAddr
	sta     _DumpAddr
	bcc     L03D8
	inc     _DumpAddr+1
	jmp     L03D8
L04D1:	ldx     #$00
	lda     (sp),y
	jmp     incsp3
L03D8:	jsr     _UpdateDump
	jmp     L03D1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ HelpHandler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_HelpHandler: near

.segment	"CODE"

	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	jsr     pushax
	lda     #$05
	jsr     pusha0
	lda     #$01
	jsr     _ActivateFrame
	jsr     _AnyKeyPrompt
	jsr     _cgetc
	ldy     #$00
	lda     (sp),y
	jsr     _Redraw
	ldx     #$00
	txa
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ DisplayPrompt (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DisplayPrompt: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp1
	lda     #$01
	ldy     #$00
	sta     (sp),y
	lda     _ActivePrompt
	ora     _ActivePrompt+1
	beq     L014B
	lda     #$28
	sec
	sbc     _PromptLength
	lsr     a
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     _PromptLength
	jsr     _chlinexy
L014B:	ldy     #$02
	jsr     ldaxysp
	sta     _ActivePrompt
	stx     _ActivePrompt+1
	ldy     #$00
	lda     (sp),y
	sta     _PromptColor
	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     _strlen
	sta     _PromptLength
	lda     #$28
	sec
	sbc     _PromptLength
	lsr     a
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     _cputsxy
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ SingleStep (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SingleStep: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	lda     _brk_pc+1
	sta     ptr1+1
	lda     _brk_pc
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$10
	beq     L0424
	cmp     #$20
	beq     L0437
	cmp     #$30
	beq     L0424
	cmp     #$40
	beq     L0432
	cmp     #$4C
	beq     L040E
	cmp     #$50
	beq     L0424
	cmp     #$60
	beq     L042F
	cmp     #$6C
	beq     L0412
	cmp     #$70
	beq     L0424
	cmp     #$90
	beq     L0424
	cmp     #$B0
	beq     L0424
	cmp     #$D0
	beq     L0424
	cmp     #$F0
	beq     L0424
	jmp     L040C
L040E:	jsr     _GetArg16
	jmp     L04D2
L0412:	jsr     _GetArg16
	jsr     ldaxi
	jmp     L04D2
L0424:	lda     _brk_pc
	ldx     _brk_pc+1
	iny
	jsr     ldaidx
	dey
	sta     (sp),y
	lda     (sp),y
	beq     L040C
	ldx     #$00
	lda     (sp),y
	bpl     L042D
	dex
L042D:	clc
	adc     _brk_pc
	pha
	txa
	adc     _brk_pc+1
	tax
	pla
	jsr     incax2
	jsr     _DbgSetTmpBreak
	jmp     L040C
L042F:	jsr     _SetRTSBreak
	jmp     incsp2
L0432:	lda     #$01
	jsr     _GetStack16
	jmp     L04D2
L0437:	iny
	lda     (sp),y
	beq     L040C
	jsr     _GetArg16
	jmp     L04D2
L040C:	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     pushax
	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _DbgDisAsmLen
	jsr     tosaddax
L04D2:	jsr     _DbgSetTmpBreak
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ RedrawStatic (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_RedrawStatic: near

.segment	"CODE"

	jsr     pusha
	lda     #$FF
	sta     _ActiveFrame
	sta     _ActiveFrame+1
	jsr     _clrscr
	lda     #$00
	jsr     _cursor
	jsr     _DrawFrames
	jsr     _HelpPrompt
	ldy     #$00
	lda     (sp),y
	jsr     pusha0
	lda     #$00
	jsr     _ActivateFrame
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ Redraw (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Redraw: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	jsr     _RedrawStatic
	jsr     _UpdateAsm
	jsr     _UpdateReg
	jsr     _UpdateStack
	jsr     _UpdateCStack
	jsr     _UpdateDump
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ GetKeyUpdate (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetKeyUpdate: near

.segment	"BSS"

L0456:
	.res	1,$00

.segment	"CODE"

	jmp     L0459
L04D3:	lda     L0456
	beq     L045F
	cmp     #$01
	beq     L0462
	cmp     #$02
	beq     L0465
	cmp     #$03
	beq     L0468
	jmp     L04D4
L045F:	jsr     _UpdateAsm
	jmp     L04D4
L0462:	jsr     _UpdateStack
	jmp     L04D4
L0465:	jsr     _UpdateCStack
	jmp     L04D4
L0468:	jsr     _UpdateDump
L04D4:	lda     L0456
	clc
	adc     #$01
	and     #$03
	sta     L0456
L0459:	jsr     _kbhit
	tax
	beq     L04D3
	jmp     _cgetc

.endproc

; ---------------------------------------------------------------
; void __near__ DrawFrame (register __near__ const struct $anon-struct-0008 *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DrawFrame: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	ldx     #$04
	jsr     regswap2
	ldy     #$0B
	jsr     subysp
	ldy     #$0B
	lda     (sp),y
	beq     L00CF
	lda     #$01
	ldy     #$00
	sta     (sp),y
	lda     #$2B
	ldy     #$07
	sta     (sp),y
	dey
	sta     (sp),y
	dey
	sta     (sp),y
	jmp     L04D6
L00CF:	lda     #$01
	ldy     #$00
	sta     (sp),y
	lda     (regbank+4),y
	ldy     #$07
	sta     (sp),y
	ldy     #$01
	lda     (regbank+4),y
	ldy     #$06
	sta     (sp),y
	ldy     #$02
	lda     (regbank+4),y
	ldy     #$05
	sta     (sp),y
	ldy     #$03
	lda     (regbank+4),y
L04D6:	ldy     #$04
	sta     (sp),y
	lda     (regbank+4),y
	dey
	sta     (sp),y
	ldy     #$05
	lda     (regbank+4),y
	ldy     #$02
	sta     (sp),y
	ldy     #$08
	lda     (regbank+4),y
	ldy     #$01
	sta     (sp),y
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     _cputcxy
	ldy     #$01
	lda     (sp),y
	jsr     _chline
	ldy     #$06
	lda     (sp),y
	jsr     _cputc
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (regbank+4),y
	jsr     _cvlinexy
	ldy     #$05
	lda     (sp),y
	jsr     _cputc
	ldy     #$01
	lda     (sp),y
	jsr     _chline
	ldy     #$04
	lda     (sp),y
	jsr     _cputc
	ldy     #$06
	lda     (regbank+4),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (regbank+4),y
	jsr     _cvlinexy
	ldy     #$0D
	lda     (regbank+4),y
	ldy     #$08
	sta     (sp),y
	ldy     #$0F
	lda     (regbank+4),y
	tax
	dey
	lda     (regbank+4),y
	ldy     #$09
	jsr     staxysp
	jmp     L0109
L0107:	ldy     #$03
	lda     (sp),y
	jsr     pusha0
	ldy     #$0C
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jsr     tosadda0
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha0
	ldy     #$0D
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     tosadda0
	jsr     pusha
	ldy     #$0C
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _cputsxy
	ldy     #$09
	ldx     #$00
	lda     #$04
	jsr     addeqysp
L0109:	ldy     #$08
	lda     (sp),y
	pha
	sec
	sbc     #$01
	sta     (sp),y
	pla
	tax
	bne     L0107
	ldy     #$0C
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	iny
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ DrawFrames (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DrawFrames: near

.segment	"CODE"

	jsr     decsp3
	lda     #$00
	ldy     #$02
L04D8:	sta     (sp),y
	cmp     #$06
	bcs     L0113
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L04D9
	inx
	clc
L04D9:	adc     #<(_Frames)
	tay
	txa
	adc     #>(_Frames)
	tax
	tya
	jsr     ldaxi
	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0A
	lda     (ptr1),y
	beq     L0114
	jsr     pushw0sp
	lda     #$00
	jsr     _DrawFrame
L0114:	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L04D8
L0113:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ ActivateFrame (int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ActivateFrame: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	lda     regbank+4
	ldx     regbank+5
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	cpx     _ActiveFrame+1
	bne     L04DC
	cmp     _ActiveFrame
	jeq     L0126
L04DC:	ldx     _ActiveFrame+1
	bmi     L0128
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	jsr     aslax1
	clc
	adc     #<(_Frames)
	tay
	txa
	adc     #>(_Frames)
	tax
	tya
	jsr     pushw
	lda     #$00
	jsr     _DrawFrame
L0128:	ldy     #$05
	jsr     ldaxysp
	sta     _ActiveFrame
	stx     _ActiveFrame+1
	txa
	bmi     L012E
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	jsr     aslax1
	clc
	adc     #<(_Frames)
	tay
	txa
	adc     #>(_Frames)
	tax
	tya
	jsr     ldaxi
	sta     regbank+4
	stx     regbank+4+1
	ldy     #$03
	lda     (sp),y
	beq     L0138
	ldy     #$05
	lda     (regbank+4),y
	clc
	adc     #$01
	ldy     #$02
L04DB:	sta     (sp),y
	lda     (sp),y
	jsr     pusha0
	ldy     #$07
	lda     (regbank+4),y
	jsr     tosicmp0
	bcs     L0138
	ldy     #$04
	lda     (regbank+4),y
	clc
	adc     #$01
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (regbank+4),y
	jsr     _cclearxy
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L04DB
L0138:	lda     regbank+4
	ldx     regbank+4+1
	jsr     pushax
	lda     #$01
	jsr     _DrawFrame
L012E:	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     _DisplayPrompt
L0126:	ldy     #$00
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ HelpPrompt (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_HelpPrompt: near

.segment	"CODE"

	lda     #<(L0163)
	ldx     #>(L0163)
	jmp     _DisplayPrompt

.endproc

; ---------------------------------------------------------------
; void __near__ AnyKeyPrompt (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AnyKeyPrompt: near

.segment	"CODE"

	lda     #<(L0167)
	ldx     #>(L0167)
	jmp     _DisplayPrompt

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ IsAbortKey (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_IsAbortKey: near

.segment	"CODE"

	jsr     pusha
	ldx     #$00
	txa
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ Input (__near__ unsigned char *, __near__ unsigned char *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Input: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp8
	lda     #$00
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     #$28
	jsr     _cclearxy
	lda     #$01
	ldy     #$05
	sta     (sp),y
	lda     #$00
	jsr     pusha
	lda     #$18
	jsr     pusha
	ldy     #$0E
	jsr     ldaxysp
	jsr     _cputsxy
	jsr     _wherex
	ldy     #$03
	sta     (sp),y
	lda     #$01
	jsr     _cursor
	ldy     #$04
	sta     (sp),y
	lda     #$00
	ldy     #$01
	sta     (sp),y
	iny
	sta     (sp),y
L0180:	jsr     _cgetc
	ldy     #$00
	sta     (sp),y
	ldx     #$00
	jsr     _isalnum
	stx     tmp1
	ora     tmp1
	beq     L0185
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldy     #$08
	cmp     (sp),y
	bcs     L0185
	ldy     #$02
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (sp),y
	sta     (ptr1),y
	ldy     #$02
	lda     (sp),y
	clc
	iny
	adc     (sp),y
	jsr     pusha
	lda     #$18
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _cputcxy
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L04E0
L0185:	ldy     #$02
	lda     (sp),y
	beq     L0193
	ldy     #$00
	lda     (sp),y
	cmp     #$08
	bne     L04E7
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$01
	sta     (sp),y
	clc
	iny
	adc     (sp),y
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     #$20
	jsr     _cputcxy
	ldy     #$02
	lda     (sp),y
	clc
	iny
	adc     (sp),y
	jsr     pusha
	lda     #$18
	jsr     _gotoxy
	jmp     L01A9
L0193:	tay
L04E7:	lda     (sp),y
	cmp     #$0A
	bne     L04E5
	ldy     #$02
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	sta     ptr1
	lda     #$00
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	lda     #$01
	jmp     L04E6
L04E5:	lda     (sp),y
	jsr     _IsAbortKey
	tax
	beq     L01A9
	lda     #$02
L04E6:	ldy     #$01
L04E0:	sta     (sp),y
L01A9:	ldy     #$01
	lda     (sp),y
	jeq     L0180
	ldy     #$04
	lda     (sp),y
	jsr     _cursor
	jsr     _DrawFrames
	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	ldy     #$06
	jsr     staxysp
	lda     #$FF
	sta     _ActiveFrame
	sta     _ActiveFrame+1
	ldy     #$09
	jsr     pushwysp
	lda     #$00
	jsr     _ActivateFrame
	ldy     #$01
	lda     (sp),y
	cmp     #$01
	jsr     booleq
	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ InputHex (__near__ unsigned char *, __near__ unsigned int *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InputHex: near

.segment	"CODE"

	jsr     pushax
	ldy     #$0A
	jsr     subysp
	ldy     #$0F
	jsr     pushwysp
	lda     #$07
	jsr     leaa0sp
	jsr     pushax
	lda     #$04
	jsr     _Input
	tax
	jeq     L01E7
	ldy     #$05
	lda     (sp),y
	ldx     #$00
	jsr     _isxdigit
	stx     tmp1
	ora     tmp1
	bne     L01BF
	tax
	jmp     L01E7
L01BF:	lda     #$05
	jsr     leaa0sp
	ldy     #$03
	jsr     staxysp
	ldx     #$00
	txa
	jsr     stax0sp
	jmp     L01CE
L01CC:	jsr     ldax0sp
	jsr     shlax4
	jsr     stax0sp
	ldy     #$02
	lda     (sp),y
	ldx     #$00
	jsr     _isdigit
	stx     tmp1
	ora     tmp1
	beq     L01D7
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$30
	jmp     L04E9
L01D7:	ldy     #$02
	lda     (sp),y
	ldx     #$00
	jsr     _toupper
	ldy     #$37
	jsr     decaxy
	ldy     #$02
L04E9:	sta     (sp),y
	ldx     #$00
	jsr     addeq0sp
	ldy     #$03
	ldx     #$00
	lda     #$01
	jsr     addeqysp
L01CE:	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	ldy     #$02
	sta     (sp),y
	tax
	beq     L04E8
	lda     (sp),y
	ldx     #$00
	jsr     _isxdigit
	stx     tmp1
	ora     tmp1
	bne     L01CC
L04E8:	ldy     #$0B
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	jsr     ldax0sp
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	ldx     #$00
	tya
L01E7:	ldy     #$0E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ ErrorPrompt (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ErrorPrompt: near

.segment	"CODE"

	jsr     pushax
	lda     _ActivePrompt
	ldx     _ActivePrompt+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     _DisplayPrompt
	jsr     _cgetc
	jsr     ldax0sp
	jsr     _DisplayPrompt
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ InputGoto (__near__ unsigned int *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InputGoto: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp1
	lda     #<(L01F3)
	ldx     #>(L01F3)
	jsr     pushax
	ldy     #$04
	jsr     ldaxysp
	jsr     _InputHex
	ldy     #$00
	sta     (sp),y
	lda     (sp),y
	bne     L04EF
	lda     #<(L01F9)
	ldx     #>(L01F9)
	jsr     _ErrorPrompt
L04EF:	ldx     #$00
	lda     (sp,x)
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ BreakInRomError (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_BreakInRomError: near

.segment	"CODE"

	lda     #<(L01FE)
	ldx     #>(L01FE)
	jmp     _ErrorPrompt

.endproc

; ---------------------------------------------------------------
; void __near__ DbgSetTmpBreak (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgSetTmpBreak: near

.segment	"CODE"

	jsr     pushax
	jsr     _DbgGetBreakSlot
	jsr     pushax
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	jsr     ldaxysp
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$80
	ldy     #$03
	sta     (ptr1),y
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ DbgToggleUserBreak (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgToggleUserBreak: near

.segment	"CODE"

	jsr     pushax
	lda     regbank+4
	ldx     regbank+5
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     _DbgIsBreak
	sta     regbank+4
	stx     regbank+4+1
	lda     regbank+4
	ora     regbank+4+1
	beq     L0209
	lda     #$00
	ldy     #$03
	sta     (regbank+4),y
	dec     _DbgBreakCount
	jmp     L0219
L0209:	lda     _DbgBreakCount
	cmp     #$0A
	bcc     L020F
	lda     #<(L0212)
	ldx     #>(L0212)
	jsr     _ErrorPrompt
	jmp     L0219
L020F:	ldy     #$03
	jsr     ldaxysp
	jsr     _DbgIsRAM
	stx     tmp1
	ora     tmp1
	bne     L0215
	jsr     _BreakInRomError
	jmp     L0219
L0215:	jsr     _DbgGetBreakSlot
	sta     regbank+4
	stx     regbank+4+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	jsr     ldaxysp
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	tya
	ldy     #$03
	sta     (regbank+4),y
	inc     _DbgBreakCount
L0219:	ldy     #$00
	lda     (sp),y
	sta     regbank+4
	iny
	lda     (sp),y
	sta     regbank+5
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ DbgResetTmpBreaks (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgResetTmpBreaks: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(_DbgBreaks)
	ldx     #>(_DbgBreaks)
	jsr     pushax
	lda     #$00
	ldy     #$02
L04F1:	sta     (sp),y
	cmp     #$0A
	bcs     L0224
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	cmp     #$80
	bne     L022B
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$03
	sta     (ptr1),y
L022B:	ldx     #$00
	lda     #$04
	jsr     addeq0sp
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L04F1
L0224:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ DbgTmpBreaksOk (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgTmpBreaksOk: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(_DbgBreaks)
	ldx     #>(_DbgBreaks)
	jsr     pushax
	lda     #$00
	ldy     #$02
L04F2:	sta     (sp),y
	ldx     #$00
	lda     (sp),y
	cmp     #$0A
	bcs     L04F4
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	cmp     #$80
	bne     L023A
	jsr     ldax0sp
	jsr     ldaxi
	jsr     _DbgIsRAM
	stx     tmp1
	ora     tmp1
	bne     L023A
	jsr     _BreakInRomError
	jsr     _DbgResetTmpBreaks
	ldx     #$00
	txa
	jmp     incsp3
L023A:	ldx     #$00
	lda     #$04
	jsr     addeq0sp
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L04F2
L04F4:	lda     #$01
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ AsmBack (unsigned int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmBack: near

.segment	"CODE"

	jsr     pusha
	ldy     #$43
	jsr     subysp
	lda     #$06
	jsr     pusha0
L0247:	lda     #$00
	ldy     #$02
	sta     (sp),y
	ldy     #$49
	jsr     pushwysp
	ldy     #$47
	ldx     #$00
	lda     (sp),y
	jsr     mulax3
	jsr     tossubax
	sec
	ldy     #$00
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	tax
	pla
	ldy     #$43
	jsr     staxysp
L0250:	ldy     #$44
	jsr     ldaxysp
	jsr     _DbgDisAsmLen
	ldy     #$43
	jsr     addeqysp
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L04F8
	inx
	clc
L04F8:	adc     #$03
	bcc     L0259
	inx
	clc
L0259:	adc     sp
	sta     ptr1
	txa
	adc     sp+1
	sta     ptr1+1
	ldy     #$44
	jsr     ldaxysp
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	iny
	lda     (sp),y
	clc
	adc     #$01
	and     #$1F
	sta     (sp),y
	ldy     #$44
	jsr     ldaxysp
	ldy     #$46
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bcc     L0250
	ldy     #$44
	jsr     ldaxysp
	ldy     #$46
	cmp     (sp),y
	bne     L04FA
	txa
	iny
	cmp     (sp),y
	beq     L0261
L04FA:	ldy     #$01
	lda     (sp),y
	bne     L04FC
	dey
	lda     (sp),y
	cmp     #$0C
	bne     L04FC
L0261:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	sec
	ldy     #$45
	sbc     (sp),y
	sec
	sbc     #$01
	and     #$1F
	asl     a
	bcc     L04F9
	inx
	clc
L04F9:	adc     #$03
	bcc     L0267
	inx
	clc
L0267:	adc     sp
	tay
	txa
	adc     sp+1
	tax
	tya
	jsr     ldaxi
	jmp     L0248
L04FC:	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	jmp     L0247
L0248:	ldy     #$48
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateAsm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateAsm: near

.segment	"CODE"

	ldy     #$2A
	jsr     subysp
	lda     _AsmFrame+8
	jsr     pusha
	lda     _AsmFrame+4
	clc
	adc     #$01
	jsr     pusha
	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     pushax
	lda     #$02
	jsr     _AsmBack
	jsr     pushax
	lda     _AsmFrame+5
	clc
	adc     #$01
	ldy     #$04
L04FF:	sta     (sp),y
	cmp     _AsmFrame+7
	jcs     L0272
	jsr     pushw0sp
	lda     #$08
	jsr     leaa0sp
	jsr     pushax
	ldy     #$07
	lda     (sp),y
	jsr     _DbgDisAsm
	ldy     #$05
	sta     (sp),y
	jsr     ldax0sp
	cpx     _brk_pc+1
	bne     L027E
	cmp     _brk_pc
	bne     L027E
	lda     #$2D
	ldy     #$0A
	sta     (sp),y
	lda     #$3E
	iny
	sta     (sp),y
L027E:	jsr     ldax0sp
	jsr     _DbgIsBreak
	stx     tmp1
	ora     tmp1
	beq     L0286
	lda     #$2A
	ldy     #$0B
	sta     (sp),y
L0286:	jsr     ldax0sp
	cpx     _AsmAddr+1
	bne     L028C
	cmp     _AsmAddr
	bne     L028C
	lda     #$01
	jsr     _revers
	lda     #$01
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$08
	jsr     leaa0sp
	jsr     _cputsxy
	lda     #$00
	jsr     _revers
	jmp     L0296
L028C:	lda     #$01
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$08
	jsr     leaa0sp
	jsr     _cputsxy
L0296:	ldy     #$05
	lda     (sp),y
	ldx     #$00
	jsr     addeq0sp
	ldy     #$04
	clc
	lda     #$01
	adc     (sp),y
	jmp     L04FF
L0272:	jsr     ldax0sp
	ldy     #$2E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ AsmArg16 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmArg16: near

.segment	"CODE"

	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     incax1
	ldy     #$01
	jmp     ldaxidx

.endproc

; ---------------------------------------------------------------
; void __near__ AsmFollow (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmFollow: near

.segment	"CODE"

	lda     _AsmAddr+1
	sta     ptr1+1
	lda     _AsmAddr
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$10
	beq     L02B0
	cmp     #$20
	beq     L02A6
	cmp     #$30
	beq     L02B0
	cmp     #$40
	beq     L0504
	cmp     #$4C
	beq     L02A6
	cmp     #$50
	beq     L02B0
	cmp     #$60
	beq     L0503
	cmp     #$6C
	beq     L02AC
	cmp     #$70
	beq     L02B0
	cmp     #$90
	beq     L02B0
	cmp     #$B0
	beq     L02B0
	cmp     #$D0
	beq     L02B0
	cmp     #$F0
	beq     L02B0
	rts
L02A6:	jsr     _AsmArg16
	jmp     L0505
L02AC:	jsr     _AsmArg16
	jmp     L0501
L02B0:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     incax2
	jsr     pushax
	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     incax1
	ldy     #$00
	jsr     ldaidx
	jsr     tosaddax
	jmp     L0505
L0503:	ldx     #$01
	txa
	clc
	adc     _DbgSP
	bcc     L0500
	inx
L0500:	jsr     ldaxi
	jsr     incax1
	jmp     L0505
L0504:	ldx     #$01
	lda     #$02
	clc
	adc     _DbgSP
	bcc     L0501
	inx
L0501:	jsr     ldaxi
L0505:	sta     _AsmAddr
	stx     _AsmAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ AsmHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_AsmHome: near

.segment	"CODE"

	lda     _brk_pc+1
	sta     _AsmAddr+1
	lda     _brk_pc
	sta     _AsmAddr
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitAsm (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitAsm: near

.segment	"CODE"

	jsr     _AsmHome
	jmp     _UpdateAsm

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateReg (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateReg: near

.segment	"CODE"

	lda     _RegFrame+4
	clc
	adc     #$05
	jsr     pusha
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$02
	jsr     pusha
	lda     _RegFrame+5
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _cputhex16
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_sr
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_a
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_x
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _brk_y
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgSP
	jsr     _cputhex8
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgCS
	ldx     _DbgCS+1
	jsr     _cputhex16
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	jsr     _gotoxy
	lda     _DbgHI
	ldx     _DbgHI+1
	jsr     _cputhex16
	ldx     #$00
	txa
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ InitReg (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitReg: near

.segment	"CODE"

	jmp     _UpdateReg

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateStack: near

.segment	"CODE"

	lda     _StackAddr
	jsr     pusha
	lda     _StackFrame+4
	clc
	adc     #$01
	jsr     pusha
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$06
	jsr     pusha
	jsr     decsp1
	lda     _StackFrame+7
	sec
	sbc     #$01
	ldy     #$00
L0509:	sta     (sp),y
	ldx     #$00
	lda     (sp),y
	sec
	sbc     _StackFrame+5
	sta     tmp1
	lda     tmp1
	beq     L033D
	bcc     L033D
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldy     #$03
	lda     (sp),y
	jsr     _cputhex8
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldx     #$01
	lda     #$00
	clc
	ldy     #$03
	adc     (sp),y
	bcc     L0507
	inx
L0507:	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _cputhex8
	ldy     #$03
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldy     #$00
	lda     (sp),y
	sec
	sbc     #$01
	jmp     L0509
L033D:	ldy     #$03
	lda     (sp),y
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ StackHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_StackHome: near

.segment	"CODE"

	lda     _DbgSP
	clc
	adc     #$01
	sta     _StackAddr
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitStack: near

.segment	"CODE"

	jsr     _StackHome
	jmp     _UpdateStack

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateCStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateCStack: near

.segment	"CODE"

	lda     _CStackAddr
	ldx     _CStackAddr+1
	jsr     pushax
	lda     _CStackFrame+4
	clc
	adc     #$05
	jsr     pusha
	jsr     decsp1
	lda     _CStackFrame+7
	sec
	sbc     #$01
	ldy     #$00
L050B:	sta     (sp),y
	sec
	sbc     _CStackFrame+5
	sta     tmp1
	lda     tmp1
	beq     L050C
	bcc     L050C
	iny
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _gotoxy
	ldy     #$03
	jsr     ldaxysp
	jsr     ldaxi
	jsr     _cputhex16
	ldy     #$02
	ldx     #$00
	tya
	jsr     addeqysp
	ldy     #$00
	lda     (sp),y
	sec
	sbc     #$01
	jmp     L050B
L050C:	lda     _CStackFrame+4
	clc
	adc     #$01
	jsr     pusha
	lda     _CStackFrame+7
	sec
	sbc     #$01
	jsr     pusha
	lda     #<(L038A)
	ldx     #>(L038A)
	jsr     _cputsxy
	ldy     #$03
	jsr     ldaxysp
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ CStackHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_CStackHome: near

.segment	"CODE"

	lda     _DbgCS+1
	sta     _CStackAddr+1
	lda     _DbgCS
	sta     _CStackAddr
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ InitCStack (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitCStack: near

.segment	"CODE"

	jsr     _CStackHome
	jmp     _UpdateCStack

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ UpdateDump (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_UpdateDump: near

.segment	"CODE"

	ldy     #$29
	jsr     subysp
	lda     _DumpAddr
	ldx     _DumpAddr+1
	jsr     pushax
	lda     _DumpFrame+4
	clc
	adc     #$01
	jsr     pusha
	ldy     #$04
	jsr     pushwysp
	lda     _DumpFrame+5
	clc
	adc     #$01
	ldy     #$05
L050D:	sta     (sp),y
	cmp     _DumpFrame+7
	bcs     L03BB
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	jsr     pushwysp
	lda     #$0A
	jsr     leaa0sp
	jsr     pushax
	lda     #$08
	jsr     pusha
	jsr     _DbgMemDump
	jsr     _cputsxy
	ldy     #$03
	ldx     #$00
	lda     #$08
	jsr     addeqysp
	ldy     #$05
	clc
	lda     #$01
	adc     (sp),y
	jmp     L050D
L03BB:	dey
	jsr     ldaxysp
	ldy     #$2E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ DumpHome (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DumpHome: near

.segment	"CODE"

	lda     #$00
	sta     _DumpAddr
	sta     _DumpAddr+1
	rts

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ GetArg16 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetArg16: near

.segment	"CODE"

	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     incax1
	ldy     #$01
	jmp     ldaxidx

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ GetStack16 (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GetStack16: near

.segment	"CODE"

	jsr     pusha
	ldx     #$00
	lda     (sp,x)
	clc
	adc     _DbgSP
	bcc     L050E
	inx
L050E:	sta     ptr1
	stx     ptr1+1
	ldx     #$01
	txa
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ SetRTSBreak (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SetRTSBreak: near

.segment	"CODE"

	lda     #$00
	jsr     _GetStack16
	jsr     incax1
	jmp     _DbgSetTmpBreak

.endproc

; ---------------------------------------------------------------
; void __near__ DbgEntry (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DbgEntry: near

.segment	"DATA"

L046F:
	.byte	$01

.segment	"CODE"

	jsr     decsp2
	lda     L046F
	beq     L0471
	lda     #$00
	sta     L046F
	jsr     _RedrawStatic
	jsr     _InitAsm
	jsr     _InitReg
	jsr     _InitStack
	jsr     _InitCStack
	jsr     _UpdateDump
L0471:	jsr     _AsmHome
	jsr     _UpdateReg
	jsr     _StackHome
	jsr     _CStackHome
	lda     #$00
	tay
	sta     (sp),y
	jmp     L0513
L0482:	lda     _ActiveFrame
	ldx     _ActiveFrame+1
	jsr     aslax1
	clc
	adc     #<(_Frames)
	tay
	txa
	adc     #>(_Frames)
	tax
	tya
	jsr     ldaxi
	ldy     #$0C
	jsr     ldaxidx
	jsr     callax
	ldy     #$01
	sta     (sp),y
	ldx     #$00
	lda     (sp),y
	jeq     L0512
	cmp     #$0A
	jeq     L04B2
	cmp     #$20
	jeq     L04AA
	cmp     #$31
	beq     L0511
	cmp     #$32
	beq     L0511
	cmp     #$33
	beq     L0511
	cmp     #$34
	beq     L0511
	cmp     #$35
	beq     L0511
	cmp     #$3F
	beq     L049A
	cmp     #$63
	jeq     L0512
	cmp     #$68
	beq     L04A2
	cmp     #$71
	jeq     L04CA
	cmp     #$72
	jeq     L04C6
	cmp     #$73
	beq     L04C0
	cmp     #$75
	beq     L049D
	jmp     L048B
L0511:	lda     (sp),y
	ldy     #$31
	jsr     decaxy
	jsr     pushax
	lda     #$00
	jsr     _ActivateFrame
	jmp     L048B
L049A:	jsr     _HelpHandler
	jmp     L048B
L049D:	jsr     _SetRTSBreak
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L0513
L04A2:	lda     _brk_pc
	ldx     _brk_pc+1
	cpx     _AsmAddr+1
	bne     L0514
	cmp     _AsmAddr
	beq     L048B
L0514:	lda     _AsmAddr
	ldx     _AsmAddr+1
	jsr     _DbgSetTmpBreak
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L0513
L04AA:	tya
	jsr     _SingleStep
	jsr     _DbgTmpBreaksOk
	tax
	beq     L048B
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L0513
L04B2:	txa
	jsr     _SingleStep
	jsr     _DbgTmpBreaksOk
	tax
	beq     L048B
	lda     #$01
	ldy     #$00
	sta     (sp),y
	jmp     L0513
L0512:	tya
	dey
	sta     (sp),y
	jmp     L0513
L04C0:	lda     _brk_pc
	ldx     _brk_pc+1
	jsr     _DbgDisAsmLen
	clc
	adc     _brk_pc
	sta     _brk_pc
	txa
	adc     _brk_pc+1
	sta     _brk_pc+1
	jsr     _InitAsm
	jmp     L048B
L04C6:	lda     _ActiveFrame
	jsr     _Redraw
	jmp     L048B
L04CA:	jsr     _clrscr
	ldx     #$00
	lda     #$01
	jsr     _exit
L048B:	ldy     #$00
L0513:	lda     (sp),y
	jeq     L0482
	jmp     incsp2

.endproc

