;
; File generated by cc65 v 2.17 - Git 582aa41
;
	.fopt		compiler,"cc65 v 2.17 - Git 582aa41"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		__poserror
	.import		__stroserror
	.import		__oserror
	.import		_ExitTurbo
	.import		_DlgBoxOk

.segment	"RODATA"

L001B:
	.byte	$00

; ---------------------------------------------------------------
; void __near__ __fastcall__ _poserror (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__poserror: near

.segment	"CODE"

	jsr     pushax
	lda     __oserror
	jsr     __stroserror
	jsr     pushax
	jsr     _ExitTurbo
	ldy     #$03
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L0012
	iny
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	beq     L0012
	ldy     #$03
	jsr     ldaxysp
	bra     L0022
L0012:	lda     #<(L001B)
	ldx     #>(L001B)
L0022:	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     _DlgBoxOk
	jmp     incsp4

.endproc

