# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_adder/design_adder.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_adder || ORIG_REF_NAME==design_adder} -quiet] -quiet

# IP: bd/design_adder/ip/design_adder_processing_system7_0_0/design_adder_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_adder_processing_system7_0_0 || ORIG_REF_NAME==design_adder_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_adder/ip/design_adder_auto_pc_0/design_adder_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_adder_auto_pc_0 || ORIG_REF_NAME==design_adder_auto_pc_0} -quiet] -quiet

# IP: bd/design_adder/ip/design_adder_processing_system7_0_axi_periph_0/design_adder_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_adder_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==design_adder_processing_system7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_adder/ip/design_adder_rst_processing_system7_0_100M_0/design_adder_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_adder_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_adder_rst_processing_system7_0_100M_0} -quiet] -quiet

# IP: bd/design_adder/ip/design_adder_scalar_add_0/design_adder_scalar_add_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_adder_scalar_add_0 || ORIG_REF_NAME==design_adder_scalar_add_0} -quiet] -quiet

# XDC: bd/design_adder/design_adder_ooc.xdc
